### ISSUE TITLE
Pilot four Trainers for two day Carpentries Instructor Training

### ISSUE THREAD

**Issue by jcoliver** [carpentries/trainers#104]
## Summary
In an effort to facilitate more Carpentries Instructor Training events, providing the option of volunteer Trainers to instruct on only one of the two days in a two-day training event may allow more Trainers to participate.

## Background
Given the volunteer nature of Carpentries Instructor Trainers, and the finite nature of time, the demand for Carpentries Instructor Training events exceeds supply. One factor could be the difficulty for some Trainers to participate in two back-to-back days of training.

### Pros
+ flexibility could increase Trainer participation, including in time zones where there are few Carpentries Instructors
+ increased Trainer participation could result in more Carpentries Instructor Training events

### Cons
+ for the two-day format, scheduling four Trainers (2 + 2) could be more complicated than scheduling two Trainers
+ requires change in Google Form whereby Trainers indicate availability
+ potentially detrimental effect on learners due to reduced continuity in instructors between the two days

## Possible Alternatives
Continue scheduling as is.

**Comment by Denubis** [comment]
As a counterpoint to this, do make sure to discuss the alternate-split events. Having run normal workshops with this many instructors, this doesn't seem like a major savings in terms of planning-effort for the drop in quality and consistency. (Though, having a "helper-instructor" at the recent 28 person instructor training was indeed quite helpful.)

**Comment by brownsarahm** [comment]
@Denubis what does "alternate-split events" refer to?

**Comment by Denubis** [comment]
@brownsarahm the 4 or 8 day event styles we've been trialling

**Comment by brownsarahm** [comment]
I'd like to suggest as trainer leadership we actually focuse on something more general than this proposal.  I think we should set up a process for local trainer communities to pilot different things and share that information back and/or for the core team to propose changes.  

Also, a missing  con I see here is the risk of lack of continuity for trainees if they have different trainers with no overlap between the two days.

**Comment by Denubis** [comment]
+1 @brownsarahm. Building a community between trainers and instructors -- and building a cohort that may be likely to teach together and act as a gathering point for carpentries communities in their local spaces is important. Without that strong relationship (not to say that community introductions aren't welcome -- but there's a huge difference between introductions and having your prior instructors vanish), we're not modelling the norms of the carpentries and providing that seed to crystalise around.

**Comment by jcoliver** [comment]
> Also, a missing con I see here is the risk of lack of continuity for trainees if they have different trainers with no overlap between the two days.

Added as a Con to the proposal

**Comment by brownsarahm** [comment]
I think what I'd like to propose instead is that we ask the core team (because I think it's a lot of work/dependent on internal processes) to work on figuring out what data would be needed and how we can collect data from local communities that are piloting things so taht 1) they can be shared 2) they can be evaluated as options for changing how centrally managed workshops are done.  My guess is this would be something that @klbarnes20 and @maneesha would do if it's appropriate for the core team?


This option of 4 trainers for a 2 day workshop could be one of the models that gets tested, but I think the necessary prerequisite to testing more things is to aggregate the things that are already being tested and have a plan for what to look at in evaluating the pilot.

**Comment by jcoliver** [comment]
I agree that a step back is warranted. What are the barriers to trainers' involvement? How can we alleviate or work around those barriers to increase the number of Instructor Training events, while maintaining quality experiences with the cadre of (largely volunteer) trainers? Could working with the Core Team on a such an assessment be a good next step?

**Comment by jcoliver** [comment]
Closing for now, in light of broader draft proposal in #127 .
