### ISSUE TITLE
Trainers Agreement Update Process Working Group

### ISSUE THREAD

**Issue by marklcrowe** [carpentries/trainers#106]
## Summary
This proposal is to recommend the establishment and terms of reference of a working group to update the Trainers Agreement

1) Issue a call for volunteers from the Trainer community to form a working group of three active Trainers plus one member of the Leadership group as chair. If possible, include at least one representative from each of the regions: North America, Europe (including UK), rest of the world. If more volunteers nominate than are needed, the Leadership Team will invite one nominee from each region to join the working group. Due 12th June for receipt of 'nominations', with selection and notification of WG in the week commencing 14th June.

2) WG to arrange by asynchronous discussion how to manage ongoing communication. Due 25th June.

3) Once communication channels are agreed, WG to identify how the Agreement is currently updated and to review feedback about that process from update released late 2020. In the interests of time, only existing feedback through standard Carpentries communication channels (e.g. Trainer meeting minutes, communications with core team, Slack, e-mail lists) and WG's personal discussions will be considered unless additional community input is considered critical. Summarise feedback to addressable key areas of concern. List of key concerns due 16th July.

4) Propose corrective actions to address key areas of concern. Formalise actions into a recommendation for Leadership group on the future process for Agreement updates, including timeline required, consultation and review activities, and roles and responsibilities. Due 2nd August for proposal to be presented to Leadership team 9th August.

## Background
Following the announcement of the [v2.0.0 Trainers Agreement ](https://github.com/carpentries/docs.carpentries.org/blob/9d02efe525929e9129a6dbb361945d3c9010baa0/topic_folders/instructor_training/duties_agreement.md)(July 2020), concerns were raised by the Trainer community about the language and requirements of the agreement. In the April 2021 Trainers Leadership meeting the Leadership group agreed to organise a working party and formalised process to update the Agreement in light of these concerns.

This was submitted to the Leadership Team meeting on 10th/11th May as a proposal to assemble a working group, review the current Trainers Agreement, and prepare an updated Agreement for ratification by the Trainer community in Aug/Sept. After discussion it was decided to reduce the scope of this proposal to focus solely on the assembly of a working group to define the process for updating the Agreement, this year and in future. The actual updating will form a later proposal based on the recommendations of this working group.

### Pros
Development of a formalised process for managing the Trainers Agreement will ensure that Trainers concerns are acknowledged and considered, and should encourage acceptance of the updated Agreements in future. Creating a working group to develop this process allows Leadership group oversight while not creating unmanageable extra workload for the Leadership group. The working group provides an opportunity for engaged Trainers to make a significant contribution to the community without the commitment of a committee or other long term role.

### Cons
This model is unlikely to achieve the timeline requested by the Leadership group (issue #77) for updating of the Trainer Agreement

## Possible Alternatives
The Leadership group could develop the process themselves. 
Selection of the working group (if more candidates volunteer than needed) could be voted in by all Trainers rather than by the Leadership group alone.
No formalised process be created, but whoever is responsible for future Agreement updates would be more active about obtaining and addressing Trainer community feedback before finalising the update.

**Comment by brownsarahm** [comment]
Timeline-wise, I think an election is tough.  Could it be a combination of an open call for volunteers and a few invitations, "selected" if necessary due to too much interest by the leadership panel person leading the effort?

**Comment by arinbasu** [comment]
Ideally an odd number of members for a working group will help to arrive at decisions when voting is needed for decision, as opposed to an even number of members where ideas can be split. Say if the working group were to consist of five members instead of four, then this might be helpful plus possibly add more breadth and representation than a three member (+ one from the leadership team) group.

**Comment by ACharbonneau** [comment]
I made a small edit, but this looks good to me.

**Comment by jcoliver** [comment]
Looks good to me, or as the cool kids say these days, lgtm

**Comment by karenword** [comment]
Given that this group will complete its recommendations Aug 2, it may be important to recognize that the process of updating the Agreement this year will have substantially progressed by then. Recommendations focused on community feedback and ratification will still be useful, but any more proximal process suggestions will have to be deferred to next time. 

I imagine their recommendations will mostly focus in this area, so it may not be necessary to make this explicit. I think the main thing is that we all agree/understand that this will be going on concurrently with work on updates this year, not entirely prior.

**Comment by arinbasu** [comment]
Looks good to me.

**Comment by brownsarahm** [comment]
I like this plan.

**Comment by jcoliver** [comment]
Approve

**Comment by marklcrowe** [comment]
I've just updated the dates to reflect the project kicking off a couple of weeks late. Because this will now be running concurrently with the 2021 update, time is less critical than it was, but I'll leave it on a tight schedule for the moment to keep things moving, and so the working group can be a short-term activity. Times can always be extended by agreement of the WG and leadership group.

**Comment by marklcrowe** [comment]
Because of the low community response and other developments that made this activity no longer necessary, this issue was closed
