### ISSUE TITLE
Trainer Agreement comments and notes

### ISSUE THREAD

**Issue by ACharbonneau** [carpentries/trainers#112]
At the May trainers leadership meeting, we decided to assess what changes need to be done to the trainer agreement while we find a committee to work on the update process. We'll use that process to facilitate the updates that we work out here.

[Link to current trainer agreement](https://docs.carpentries.org/topic_folders/instructor_training/duties_agreement.html)

**Comment by brownsarahm** [comment]
Noting some meeting minutes that capture previous concerns from trainers:


[July-August 2020](https://github.com/carpentries/trainers/blob/main/minutes/July-August_2020_Notes.md) 
_note this is multiple meetings in one file_
