### ISSUE TITLE
Proposal to approve 2021 curriculum update process (async)

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#141]
This document is submitted to inform Trainers Leadership about the process by which the most recent update to the Instructor Training curriculum has been implemented and reviewed by the Trainer community. [Updates](https://github.com/carpentries/instructor-training/pull/1215) will be merged to the main repository immediately upon approval of this process by Trainers Leadership. Approval of this process does not indicate endorsement of the same process in future updates, only recognition that the process used in this case is adequate for release.

## Updating Process:
Updates were performed in a separate repository ([data-lessons](https://github.com/data-lessons/instructor-training)) intended as a sandbox for lesson design. Plans for updates were outlined and priorities discussed with the IT curriculum Maintainers. Implementation was carried out in 3 phases:

- Themed PRs to the data-lessons repository, with review requested from Core Team and Maintainers
- General PRs to improve cohesion and timing
- Onboarding and Pilot testing by Trainers
- General PR to respond to feedback

## Community Review Process:
Community engagement was requested at multiple points.

- Themed PRs were noted & linked at the [March Trainer meeting](https://github.com/carpentries/trainers/blob/it_maintainance/minutes/2021-03-04.md) 
- Anticipated timeline and process for completing updates was presented at the [April Trainer Meeting](https://github.com/carpentries/trainers/blob/it_maintainance/minutes/2021-04-15.md)
- Fully drafted updates and plans for onboarding were presented at the [May Trainer Meeting](https://github.com/carpentries/trainers/blob/it_maintainance/minutes/2021-05-06.md) 
- Onboarding sessions were repeatedly announced via [Topicbox](https://carpentries.topicbox.com/groups/trainers/T49becb7123517b95-Md84d129028387087210a74e1/curriculum-updates-and-review-sessions) (6 messages). All interest in attending was accommodated, including via 1:1 meetings.
- June - August (and beyond) Trainer meetings included discussion of pilot trainings using new curriculum
- Survey sent out via Topicbox October 5 ([reminder Oct 13](https://carpentries.topicbox.com/groups/trainers/T984e517df5473d1d-M09bd889cfe2e360ff3bd4183/curriculum-updates-survey-reminder)) announced & requested feedback on impending release of final curriculum.

## Feedback Response Process:
Initial updates were grounded in community feedback, including multiple Issues addressed as well as accumulated feedback shared in Trainer meetings and Trainer Training. Feedback was received during the updating process via many (many) channels:

- Comments on PR to main repository
- Issues & PRs in data-lessons repository
- Discussion in Trainer meetings
- Discussion in onboarding sessions
- Surveys

Feedback has now been addressed to the greatest extent possible and updates are ready for release.

**Comment by marklcrowe** [comment]
Approved

**Comment by brownsarahm** [comment]
For context, we approved previously that we can approve thing asychronously once they've been discussed. We discussed this at the 2021-10 meeting. 

I approve.

**Comment by ACharbonneau** [comment]
approve :)

**Comment by jcoliver** [comment]
Approve!

**Comment by arinbasu** [comment]
Approved
