### ISSUE TITLE
Trainer Certification Renewal (to replace Trainer Agreement)

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#143]
**Proposal: Trainer Certification Renewal**

This proposal would replace the [Trainer Agreement](https://docs.carpentries.org/topic_folders/instructor_training/duties_agreement.html#trainer-agreement). [Trainer Alumni Status guidelines in the Handbook](https://docs.carpentries.org/topic_folders/instructor_training/duties_agreement.html#trainer-alumni-status) would also be updated as needed. 

Trainer Certification will expire and be renewed annually in March. New Trainers who have not yet been certified for a full year in March will be automatically renewed for another year.

Certification may be renewed by: 
A) (automatic) participating in curriculum and community activities during the prior year, as described below **OR**
B) (within 1 year of expiration) meeting with the Director of Instructor Training (DIT) to discuss curriculum and community as well as plans for participation in the coming year **OR**
C) (>1 year post expiration) re-activation as currently detailed in Handbook (review Trainer Training curriculum, observe part of an Instructor Training workshop, and meet with Director of Instructor Training to catch up and discuss plans, including re-introduction to the Trainer community via meetings or other arrangements.)

In the case of A, above, certification will be automatically renewed when activities are self-reported and approved by Trainers Leadership. Participation requirements for automatic renewal are **at least:**
- teaching 1 Instructor Training event, and
- hosting 2 teaching demos, and
- attending 4 Trainer community meetings 

OR 

- equivalent engagement with curriculum, trainees, or the Trainer community, as approved by the trainer leadership

**Proposed timeline**
November-December: request for comments from Trainer community
January: ratification, in combination with Trainers Leadership elections
March: implement renewal process in cooperation with new Leadership

**Comment by jcoliver** [comment]
+ teaching 1 Instructor Training event, and
+ hosting 2 teaching demos, and
+ attending 4 Trainer community meetings

OR

+ equivalent engagement with curriculum, trainees, or the Trainer community

**Comment by karenword** [comment]
Thanks -- updated!

**Comment by brownsarahm** [comment]
For this, what do we provide to the trainer community for ratification?

**Comment by karenword** [comment]
We will close this issue to comments when the election opens, and will link to this issue from the ballot for ratification.

**Comment by brownsarahm** [comment]
added, ", as approved by the trainer leadership" to equivalent line to make it more explicit, in line with that the [interpretation is a leadership power](https://github.com/carpentries/trainers/blob/main/powers_responsibilities.md)

**Comment by karenword** [comment]
Note in response to questions posed at the meetings on February 3: "Equivalent" activities are not included in this proposal because we anticipate a wide range of equivalent activities that may evolve over time. It will not be necessary to request any exception when reporting equivalent activities. Trainers Leadership will be entrusted with ensuring that this process is clear, friendly, and fair.

**Comment by karenword** [comment]
This process was ratified as of 16 February, 2022. It received 94% approval in an election with 43% turnout among eligible voters.

**Comment by karenword** [comment]
PR submitted to handbook: https://github.com/carpentries/docs.carpentries.org/pull/825
