### ISSUE TITLE
Provide clarity on relevance of quorum for Trainers Leadership meetings

### ISSUE THREAD

**Issue by jcoliver** [carpentries/trainers#164]
## Summary
The Trainers Leadership [Meeting rules document](https://github.com/carpentries/trainers/blob/main/policy/leader_meeting_rules.md) defines a quorum, but quorum is not referenced in any other part of the rules document. This proposal advocates for explanation of when quorum is necessary (for synchronous votes).

## Background
The meeting rules document guides how decisions are made in Trainers Leadership meetings. The definition of quorum is intended to make it clear when synchronous decisions can be made. However, the document lacks a clear explanation of how quorum is implemented in decision making during the meetings.

## Implementation
Revise point 4 in **Making Decisions** to read (changes italicized):

After the sponsor presents the proposal, a sense vote is cast for the proposal prior to any discussion. _If quorum is met, the vote can be done synchronously. If quorum is not met, the vote would be taken asynchronously through the GitHub issue conversation. Positions on the proposal are_:
+ Who likes the proposal?
+ Who can live with the proposal?
+ Who is uncomfortable with the proposal?

## Decision Factors
+ Do the revisions make it clear how quorum is to be used?
+ Would restriction of synchronous decisions place undue delays on decision making process?

### Pros
+ Clarifies use of quorum

### Cons
+ Places restrictions on asynchronous minutes and may delay decisions

## Possible Alternatives
+ Remove mention of quorum entirely from meeting rules

**Comment by paocorrales** [comment]
I like the proposal. 

Having said that, we should pay attention in case a decision is delayed. Although it may not happen :D

**Comment by brownsarahm** [comment]
i like this proposal. 

Pao, can you expand on what we should pay attention to?

**Comment by marklcrowe** [comment]
I like this proposal

**Comment by jcoliver** [comment]
I like this proposal
