### ISSUE TITLE
Implementation proposal for Certification Renewal

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#167]
## Summary
Certification renewal needs a process. Core Team will carry out all tasks that involve established criteria and will make recommendations to facilitate decision-making in other cases; Trainers Leadership will provide oversight and subjective review.

## Background
The [certification renewal process](https://docs.carpentries.org/topic_folders/instructor_training/duties_agreement.html#certification-renewal-process) was approved by the community in February. We now need a plan for implementation, which is should begin in March.

## Implementation
- Core team creates Google form for Trainers to self-report activities - draft to be presented at March 16 meeting with this proposal
- Core team contacts Trainers to request form response - distribute by March 25, deadline April 7
- Core team identifies candidates for automatic renewal based on trainings & demos - April 11
- Core team proposes criteria for automatic renewal based on alternate activities & identifies candidates who qualify - April 11
- Core team identifies candidates who do not meet criteria for automatic renewal or did not respond to the form -  April 11
- Trainers Leadership reviews & approves or requests changes - discuss at meeting (April 13 or 20)
- Core team implements badge renewal & requests for re-activation - April 29

## Decision Factors
- involves time-sensitive work -- deadlines should be set to be manageable for all

### Pros
- hopefully everyone will have less trepidation about this new process once it is complete
- recognizing contributions formally through may offer a small morale boost

### Cons
- will involve making a lot of noise to get responses, not too long after doing that for elections and quarterly scheduling
- delicate work to get messaging right and make this process positive and inclusive; this could go wrong.

## Possible Alternatives
- delaying implementation (despite documentation timeline)

**Comment by karenword** [comment]
After further consideration of feedback provided on the form by Leadership, Core Team has determined that we should take the time to pursue some automation of the renewal process using information in our database. This will take some time, but will make the process easier and less redundant for Trainers. Revised timeline options will be discussed at the next Leadership meeting.

**Comment by karenword** [comment]
Leadership has discussed and will allow up to 1 month for us to complete automation. If we are not able to complete this process within a month, we will carry out the original plan (with apologies) and wait to next year to improve the process.

**Comment by karenword** [comment]
Update: we have a good plan for automating renewal as much as possible based on the data we have, including customized template emails and a google form to collect additional information only as needed. Implementing this will take more time, but Leadership has indicated a preference for proceeding with this plan despite the delay. @maneesha estimates late June for implementation. Submitting here for formal re-approval of the timeline.

**Comment by marklcrowe** [comment]
I approve the updated timeline proposal.

**Comment by brownsarahm** [comment]
i like the timeline proposal

**Comment by karenword** [comment]
This process is complete!
