### ISSUE TITLE
March 2022 EC Report process

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#168]
## Summary

As outgoing Chair, Sarah Brown will lead this process creating an outline and assigning specific tasks to other members of the panel. This will include improving documentation and completeness of the tools to help generate necessary links. 

## Background

For the [previous report](https://github.com/carpentries/trainers/blob/main/reports/2021-09-leadership-to-ec.md) we divided sections and Sarah compiled as active chair.  

As the next report is mostly about the previous term it makes sense for the second report "as chair" to be the one done on an outgoing basis.  A better future plan is that a chair does the report as their last action before the new panel begins. 

## Implementation

1. Sarah will create a draft pull request with the report outline and tag others on what specific things they should add
2. all add as requested and discuss
3. when completely filled in, Sarah will convert from a draft to ready for approval
4. All approve
5. Sarah or last approver can merge
6. Sarah will send to EC with introduction to the new chair and Karen in cc

### Pros

- allows new chair time to acclimate before leading report
- mostly asynchronous approval, more flexible around time zones. 

### Cons

- prevents new chair from structuring report
- doesn't leave synchronous discussion time for the report itself

## Possible Alternatives

- new chair can lead 
- report may be separate proposal for meeting approval instead of asynchronous approval

**Comment by jcoliver** [comment]
Addressed in #178
