### ISSUE TITLE
Rubric update and promotion plan for Open Instructor Training

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#172]
## Summary
Core Team would like to invite applications to Open Instructor Training from trainees willing to teach centrally organised workshops, and assign points for this commitment as a "current recruitment push"

## Background
Open Instructor Training provides Instructor Training for free to individual applicants. The rubric we currently use to score applications is housed in the [Instructor Training Curriculum repository](https://github.com/carpentries/instructor-training/blob/gh-pages/files/rubric.md). Ranking applicants has been identified as a [power of Trainers Leadership](https://github.com/carpentries/trainers/blob/main/powers_responsibilities.md), and maintaining the rubric is a responsibility.

## Implementation
Core team will:
- update the rubric to add commitment to teach centrally organised workshops to the list of current recruitment push criteria
- design and implement a plan to promote Open Instructor Training and communicate instructions for indicating commitment to teach centrally organised workshops in the application (the application itself will not be changed).

### Pros
- Fees for centrally organised workshops are an important part of making The Carpentries more sustainable. We currently have limited funds that have 'no strings attached'. Since the pandemic and the shift to teaching online, we have experienced both an increase in demand and a decrease in availability of Instructors to teach centrally organised workshops. If successful, this could relieve significant pressure on that program.

### Cons
- If successful, this will increase the volume of applicants to our Open Instructor Training program. Applicants who are not willing to teach centrally-organised workshops may experience longer wait times before being accepted for training.

## Possible Alternatives
- We could promote the program and encourage applications from trainees willing to teach centrally organised workshops *without* changing the rubric. However, this may result in more delayed admission or rejection of willing applicants.

**Comment by brownsarahm** [comment]
This was approved on 4/15 see #[b9b8699](https://github.com/carpentries/trainers/commit/b9b8699abe7c9db59c6dfde23570236f70f02026)

**Comment by brownsarahm** [comment]
this was completed in the [IT curriculum](https://github.com/carpentries/instructor-training/commit/e29ab8ad13fd123f500c0854e42897a6529727a7)
