### ISSUE TITLE
Clarify Power for EC in documents without a vote

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#176]
## Summary

Change the trainer leadership power, "Interpret Trainer Certification Renewal data" to  "Interpret Trainer Certification Renewal Participation Requirements" and make that subheading explicit in the trainer certification renewal for clarity. 

## Background

The EC is planning to vote on our approval at their May meeting, but they requested clarification of the power that currently reads, "Interpret Trainer Certification Renewal data".  PR #175 proposes to change that to align more tightly with the (approved by a trainer vote) Certification Renewal Process, to read, "Interpret Trainer Certification Renewal Participation Requirements" which matches the section of the certification renewal language.  This power is intended to allow the leadership panel to interpret the requirements in therms of what trainers do. The leadership panel approved #167 as the implementation plan for 2022, and we want to have the flexibility to change that detailed process year over year to suit technology but keep the powers clear enough that the community knows what the leadership can do. 
 

## Implementation

- Any member of leadership may Merge #175 without having trainers vote to approve the language change to the powers
- Sarah will open a PR to [add a subheading](https://github.com/carpentries/docs.carpentries.org/compare/main...brownsarahm:patch-3#diff-09f30059956a102c99267f7b6ffaa8368be7dc704733b88dd1d0edfeb86f127dR31) to the Certification Renewal in the handbook. 

### Pros

- this gets the change made quickly and without requiring work from all trainers

### Cons

- changing our own powers without approval is not strictly speaking allowed by the documents that have been voted on

## Possible Alternatives

- ask trainers to vote on this soon (coinciding with renewal process) 
- ask trainers to vote on this at the next regular election, and remain in a semi-approved state longer.

**Comment by jcoliver** [comment]
I like this proposal

**Comment by paocorrales** [comment]
I like this proposal

**Comment by paocorrales** [comment]
I like this proposal

**Comment by brownsarahm** [comment]
I like this proposal

**Comment by marklcrowe** [comment]
I like this proposal

**Comment by paocorrales** [comment]
I like this proposal
