### ISSUE TITLE
Use consistent naming for Trainers Leadership Committee

### ISSUE THREAD

**Issue by jcoliver** [carpentries/trainers#193]
## Summary
Throughout this repository, as well as the Carpentries Handbook, a consistent name should be applied to the Trainers Leadership Committee.

## Background
The group is recognized by the Executive Committee as a Committee, but legacy references include names like "leadership panel" and "leadership group"

## Implementation

+ To make this change in this repository, documents in the top-level folder of this repository, as well as the policy folder will be searched for references to this committee and updated. The work will be done outside of regular meeting time and updates will be submitted as a pull request.
+ A corresponding search and replace will also take place on a fork of the [Carpentries Handbook repository](https://github.com/carpentries/docs.carpentries.org).

### Pros
Using consistent language will ensure clarity.

### Cons
Some legacy references may be lost, although Git versioning will preserve them (in some form).

## Possible Alternatives
Leave documents as-is, but use "Trainers Leadership Committee" for all future references.

**Comment by brownsarahm** [comment]
I like this proposal and I think we should make the Implementation section a checklist to track progress if it is approved.

**Comment by jcoliver** [comment]
Mark and Pao liked in 2022-07-20 Trainers Leadership meeting.

**Comment by bonnyad** [comment]
I like this proposal

**Comment by jcoliver** [comment]
Files that need changing:
+ governance.md
+ powers_responsibility.md
+ README.md
+ policy/CheckoutProcessGovernance.md
+ policy/it_curriculum_maintenance.md
+ policy/leader_meeting_rules.md
+ policy/request_for_comment.md

**Comment by jcoliver** [comment]
The file policy/it_curriculum_maintenance.md could use some attention; it refers to a "leadership panel" that I think is a different entity than the Trainers Leadership Committee.

**Comment by marklcrowe** [comment]
My feeling was that did mean the Leadership Committee. I'll add it to the agenda now for discussion at the next meeting.

**Comment by brownsarahm** [comment]
that file does mean leadership committee...

**Comment by jcoliver** [comment]
Addressed in PR #213
