### ISSUE TITLE
[Trainer Meeting]: When trainees don't seem ready

### ISSUE THREAD

**Issue by JCSzamosi** [carpentries/trainers#199]
### A short title

When trainees don't seem ready

### Introduce the topic

I was hoping we could have a discussion about what we can do as trainers when there is a trainee in a workshop whose level of engagement or behaviour in a training makes us worried that they may not be ready to teach Carpentries workshops, even if they've passed all the on-paper requirements.

### Which trainer meeting time would you host?

- [ ] Meeting 1 (UTC 14:00)
- [X] Meeting 2 (UTC 22:00)
- [ ] None
- [ ] other (explain below)

### Are there any scheduling concerns?

I can host this week's meeting 2. Other weeks may have scheduling constraints, so I'd like to know which week you want to do this topic before I say for sure which meeting I'm available to attend.

**Comment by brownsarahm** [comment]
this topic was hosted in meeting 2 on [July 7](https://github.com/carpentries/trainers/blob/main/minutes/2022-07-07.md)

**Comment by marklcrowe** [comment]
Covered in July 2022 meeting
