### ISSUE TITLE
[Trainer Meeting]:  Promoting Centrally-Organised Workshops

### ISSUE THREAD

**Issue by klbarnes20** [carpentries/trainers#200]
### A short title

Promoting Centrally-Organised Workshops 

### Introduce the topic

Let's discuss centrally-organised workshops! We will do a Q & A about why we might want to encourage our trainees to teach centrally-organised workshops and how we can go about promoting them.

### Which trainer meeting time would you host?

- [X] Meeting 1 (UTC 14:00)
- [X] Meeting 2 (UTC 22:00)
- [ ] None
- [ ] other (explain below)

### Are there any scheduling concerns?

N/A

**Comment by brownsarahm** [comment]
This topic was hosted in meeting 1 on [july 7](https://github.com/carpentries/trainers/blob/main/minutes/2022-07-07.md)

**Comment by marklcrowe** [comment]
Covered in July 2022 meeting
