### ISSUE TITLE
List of current Leadership members on Trainers Leadership Page

### ISSUE THREAD

**Issue by klbarnes20** [carpentries/trainers#204]
Hi all, 

I was looking for the list of current Trainers Leadership members yesterday and couldn't find it. Today I noticed it is on the main Trainers repo page, but can we also add it to the Trainers Leadership page or (if we don't want to increase maintenance) at least link back to the list?

Thanks!

**Comment by brownsarahm** [comment]
can you link to the trainer's leadership page you were looking for it on?

**Comment by klbarnes20** [comment]
Yes, sorry. Just this [governance page](https://github.com/carpentries/trainers/blob/main/governance.md). I know this is the official governance documentation, so maybe it doesn't make sense to list members here. But maybe we can link to where current membership can be found.
