### ISSUE TITLE
Revise guide for proposing Trainer meeting topics

### ISSUE THREAD

**Issue by jcoliver** [carpentries/trainers#218]
(for lack of a better place to put this)

+ To **host** a meeting, review the meetings that are already scheduled ("Upcoming Meetings" tab) and those that have yet to be scheduled ("Proposed" tab) at the [Trainers meeting scheduling page](https://github.com/orgs/carpentries/projects/4/views/2). If you find a topic you would be interested in hosting, (1) click the title of the meeting you are interested in (in the "Upcoming Meetings" or "Proposed" tabs) to see more information about the proposed topic; then (2) scroll down to leave a comment in the dialog box below the proposal to indicate if you would like to host or co-host and which meeting(s) you can attend.
+ To **propose** a topic, we ask that you create a new Issue on this GitHub repository. Go to the [new issues page](https://github.com/carpentries/trainers/issues/new/choose) and click the Get started button for "Template for Trainer Meeting Topics". Fill in the form, including a title for the Issue (which can be the same as the title of the proposed Trainer meeting topic). Before proposing a topic, we suggest you view topics that have already been proposed or scheduled at [Trainers meeting scheduling page](https://github.com/orgs/carpentries/projects/4/views/2).

See the [trainer meeting pad](https://pad.carpentries.org/trainers) for more information on the meetings or the [meeting minutes](https://github.com/carpentries/trainers/tree/main/minutes) for information about past meetings.

**Comment by brownsarahm** [comment]
note: I directly edited above to remove "just" 

I think the goal is to put this at the top of the etherpad for now? 

we could link directly to that issue type if we wanted 
```
[create a new "trainer meeting topic" issue](https://github.com/carpentries/trainers/issues/new?assignees=karenword&labels=trainermeeting&template=trainer_meeting_topic.yml&title=%5BTrainer+Meeting%5D%3A++a+short+title+)
```

**Comment by jcoliver** [comment]
Heh. Still using the "J" word am I.

I wrote the above with the Etherpad in mind, and I think we can also use it in that little README that accompanies the Project page, too.

**Comment by karenword** [comment]
I tried following these instructions and it was a little rough. I think "leave a comment in the thread dialog" only made sense after I got it right. 
Maybe "1) click the title of the meeting you are interested in to see more information about the proposed topic. 2) scroll down to *leave a comment* in the dialog box below the proposal to indicate if you would like to host or co-host and which meeting(s) you can attend. *do not use the check boxes* as these are for the original proposal only." <- that last piece because I noticed I could check the boxes, and that seems wrong.

**Comment by brownsarahm** [comment]
We can edit the proposal as maintainers, but people who are not maintainers on this repo cannot check the boxes anyway (unless they created the proposal)

**Comment by jcoliver** [comment]
Thanks, @karenword . Updated text per your suggestion.

**Comment by jcoliver** [comment]
Added text to [Trainers Etherpad](https://pad.carpentries.org/trainers) and the [Trainer Meetings Project page](https://github.com/orgs/carpentries/projects/4/views/2).
