### ISSUE TITLE
[Trainer Meeting]: Trainers Show & Tell

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#220]
### A short title

Trainers Show & Tell

### Introduce the topic

Trainers have a lot of different practices that we all do, but each of us does many of them our own way.  I think a good way for us to learn from one another would be to spend a meeting sharing practices in a sort of round robin fashion with Q&A.  We (core team + leadership) can help start by modeling some of our own and/or reaching out to people we have heard from to encourage them to volunteer and/or we can build a queue of topics during the icebreaker.  

potential seeding icebreaker: What is one thing you want to learn from other trainers and/or one thing you want to share with other trainers? 

This meeting is also an opportunity to begin collecting content for the trainer guide! 

### If you would like to host, which trainer meeting time would you host?

- [ ] Meeting 1 (UTC 14:00)
- [ ] Meeting 2 (UTC 22:00)
- [ ] I do not want to host
- [X] other (explain below)

### Are there any scheduling concerns?

I can host both if November 1st meeting, 2nd meeting only if November 2nd meeting, but I cannot attend the 1st December meeting.

**Comment by marklcrowe** [comment]
Completed in November meeting
