### ISSUE TITLE
[Trainer Meeting]:  Trainers Leadership Committee -Why join/ Recruitment

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#222]
### A short title

Trainers Leadership Committee Information

### Introduce the topic

Before/during the nomination period we could use a meeting for the current leadership to answer questions about what it is like to be on the committee.  We could also demystify some of the procedures/ease concerns of potentially interested but hesitant prospective members. 

### If you would like to host, which trainer meeting time would you host?

- [ ] Meeting 1 (UTC 14:00)
- [ ] Meeting 2 (UTC 22:00)
- [ ] I do not want to host
- [ ] other (explain below)

### Are there any scheduling concerns?

probably first December meeting [per governance](https://github.com/carpentries/trainers/blob/main/governance.md) but possibly second December if we use that?

**Comment by karenword** [comment]
Since Leadership will be preparing a report to the EC, this would also be a good time to share that report with the community.

**Comment by brownsarahm** [comment]
(at least)  I will be at the first meeting; Jeff & Mark at the second
