### ISSUE TITLE
Recommended Changes to Instructor Training Checkout 

### ISSUE THREAD

**Issue by klbarnes20** [carpentries/trainers#226]
## Summary

The Core Team undertook a project to consult the community on the Checkout process and how it could serve them better. This report is a summary of what we learned from the community. It ends (starting on page 7) with a list of recommended changes to improve the Checkout Process. 

[Instructor Training Checkout: What We Learned and Recommendations (December 2022)](https://docs.google.com/document/d/1vknKtkYwV3r74miLTqOlXB5h2yPm4b81Ui5eI5jH3ck/edit#heading=h.eenj9ulhdk5k)

## Background
Please see the report linked above for more background. 

## Implementation
Trainers Leadership will be discussing this proposal at their next meeting on December 8. They will be asked to approve as is, request changes, or reject. Once they have decided on the changes, the Core Team will create an implementation plan. Implementation will be in 2023. 

## Decision Factors
Please see the report linked above for a discussion of the rationale for each recommended change.

**Comment by sstevens2** [comment]
Very happy with all the suggested changes to checkout and other suggested changes! Thanks @klbarnes20!

**Comment by ndporter** [comment]
Looks great overall! Thanks @klbarnes20 and everyone who contributed!

I wonder whether something could be used to create an on-demand sort of trigger for teaching demos and welcome sessions (e.g. where new instructors provide availability and preferred dates then once a threshold number have indicated one it kicks it up to schedule a leader). Even if it's a little complicated on the scheduling end and might require more flexibilty from core team, it avoids the schedule and cross your fingers approach that leads to empty sessions and people who can't find one.

**Comment by jcoliver** [comment]
One note on Recommendation 1 (choosing a single episode to teach): We should make it very easy for trainees to identify the episode they will teach. The current [list of good starting points](https://carpentries.github.io/instructor-training/demo_lessons/index.html) is a good, well, starting point, but could be enhanced by replacing "any other episode" with actual episode names.

**Comment by elletjies** [comment]
Hi all, I would like to pick your brains on how we can support our African community members during checkout, especially those from South Africa and Zimbabwe. They are currently experiencing [load shedding](https://www.westerncape.gov.za/110green/files/atoms/files/Load%20Shedding%20FAQ%202019_FINAL_2.pdfl) for up to 12.5 hrs a day. This will hinder them from participating in the checkout process as they stand now. How can we support our instructors in training during this difficult time? Will they be able to submit a recorded teaching demo? Add another contribution as part of the checkout process. Could we deal with this on a case-by-case basis.

**Comment by karenword** [comment]
We now have text at the top of the teaching demos etherpad with a link to our accomodations request form. This is the best means for everyone with accessibility challenges to request accomodations that work for them. Other changes are also now complete as of 14 August 2023, so closing this issue.
