### ISSUE TITLE
Update certification renewal to reflect roles vs. badges

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#231]
## Summary
The Carpentries database now has an Active role that is separate from the Trainer badge. We need to update our language to reflect this change. A few other improvements have been included

Please see draft PR at the handbook repo: https://github.com/carpentries/docs.carpentries.org/pull/878

**Comment by marklcrowe** [comment]
Address in https://github.com/carpentries/docs.carpentries.org/pull/878 after ratification by Trainer community
