### ISSUE TITLE
[Trainer Meeting]:  Create learner profiles for Instructor Training

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#237]
### A short title

Create learner profiles for Instructor Training

### Introduce the topic

The new Workbench has a built-in page for Learner Profiles. We should create some! This will be fun to hack on together.

### If you would like to host, which trainer meeting time would you host?

- [ ] Meeting 1 (UTC 14:00)
- [X] Meeting 2 (UTC 22:00)
- [ ] I do not want to host
- [ ] other (explain below)

### Are there any scheduling concerns?

I can host both meetings, especially after the US time change, but would also be great if someone else wants to host one or both!

**Comment by karenword** [comment]
We could possibly do this as a second half to the Accessibility meeting, as that may not need the full hour.

**Comment by ragamouf** [comment]
This was not actioned for 12 months, so the time is not right for TLC to take it on as a task. I suggest we  close this issue, and ask Trainer community on slack if this is something that would be useful for them, and if there is capacity for Trainers to co-develop together.
