### ISSUE TITLE
Update for 2023 Leadership and Meeting schedule

### ISSUE THREAD

**Issue by maneesha** [carpentries/trainers#238]
This repo's readme lists the 2022 leadership group and the 2022 meeting schedule.  This should be updated for 2023.

**Comment by paocorrales** [comment]
We're having the onboarding meeting for the new committee next week 🎉

**Comment by brownsarahm** [comment]
leadership change over is actually March , so you all could probably also note that in the readme to prevent future confusion.

**Comment by marklcrowe** [comment]
Leadership group and meeting details have been updated in the readme.
