### ISSUE TITLE
[Trainer Meeting]:  Implementing Learner Profiles

### ISSUE THREAD

**Issue by ndporter** [carpentries/trainers#240]
### A short title

Implementing Learner Profiles

### Introduce the topic

The [learner profiles section](https://carpentries.github.io/instructor-training/18-preparation/index.html#anticipate-your-audience) in training is often skipped or shortened, but thinking ahead about different types of learners can support flexible and equitable learning and deal with common issues like heterogenous groups of learners.

Let's talk about how learner profiles can be useful (or problematic, for example when stereotypes sneak in) and whether there are ways we can support these in instructor training, technical lessons and notes, or in other ways and settings!

### If you would like to host, which trainer meeting time would you host?

- [X] Meeting 1 (UTC 14:00)
- [X] Meeting 2 (UTC 22:00)
- [ ] I do not want to host
- [X] other (explain below)

### Are there any scheduling concerns?

I'm glad to host both meetings but not before July (and glad to let someone else take lead if this moves earlier).

**Comment by ragamouf** [comment]
This idea is older than 12 months, and didn't explicitly surface in the survey of trainer community for what they want to talk about in trainer meetings. I recommend closing this issue.
