### ISSUE TITLE
Evaluate potential changes to Trainer Meeting schedule

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#245]
## Summary
Evaluate potential changes to Trainer Meeting schedule, including moving Meeting 2 to a later time or adding a (community-hosted?) 3rd meeting time.

## Background
In the past we have polled for meeting times. However, uneven time zone distribution in our community means that 'majority rule' can be systematically exclusionary. We regularly receive feedback that either a change to current meeting times or addition of a 3rd meeting time would be appreciated. Before implementing a change, it would be useful to consider pros, cons, and constraints on various options.

## Implementation
We will begin by asking Trainers currently in attendance at Meeting 2 about the consequences of moving that meeting to a later time. We will ask at at least 2 meetings to get a good sample of Trainers in attendance. This will help us to anticipate how many current attendees may lose access if this meeting time changes.
Other options include re-polling the community, seeking volunteer hosts for a regular or less frequent (e.g. quarterly) 3rd meeting time slot, and brainstorming additional ideas with the community.

## Decision Factors
This is a decide-to-decide proposal which has already been discussed to some degree; a separate proposal will be submitted once a preferred course of action becomes clear.

**Comment by karenword** [comment]
Update: Attendee surveys at recent meetings suggest minimal impact of moving Meeting 2 1 hour later (23:00 UTC). I suggest we implement this change.

**Comment by marklcrowe** [comment]
Committee approved 20/6/23, Karen to update schedule. Will review meeting attendance over the next few months to evaluate whether the change has allowed more people to join
