### ISSUE TITLE
Implementation of Checkout Changes, 2023

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#251]
## Summary
Reference #226 - this proposal addresses previously approved recommended changes to checkout that are actionable now, describing planned steps and a timeline for implementation.

## Background
In this first effort towards implementing recommended changes, we will change the requirements for trainees to complete checkout. Associated infrastructure updates will support these changes. They are:
- Teaching Demonstration: trainees will be asked to choose a single appropriate episode, rather than preparing a full lesson and having the Trainer select an episode to teach.
- Welcome session: this specific type of community discussion will now be required. These sessions are targeted towards new community-members and include additional onboarding content for Instructors. Attendance at other community programming can count towards the next step.
- "Get Involved": Any step towards involvement in The Carpentries may be submitted for this step, but the following items will be suggested: 
      - Serve as an Instructor or a Helper at a workshop
      - Attend a Curriculum-specific onboarding
      - Attend an Instructor Meeting, regional call, or other community programming
      - Submit a contribution to a Lesson, Glossario, or other Carpentries repository

## Implementation
Because Trainers are responsible for explaining checkout requirements to Instructor trainees, there are two major steps to rollout:
- Step 1: Trainer review and onboarding to drafted guidelines and documentation
      - June 1 Trainer meetings
      - June 15 Trainer meetings
      - Email with links to draft documentation to Topicbox
      - Reminders in the #Trainers channel on Slack
      - Reminders in 30-day and 1-week email templates sent to Trainers preparing to teach
- Step 2: General community rollout. 
      - July 10 Blog post
      - July 11-20 Community discussions
      - July 10 Emails to members, discussion-hosts, and community lists
      - Emails to trainees from past 1 year who have not yet completed checkout
      - Newsletter
      - New "checkout-helpdesk" Slack channel
- Handling trainees mid-checkout
      - Previously completed checkout steps will be transferred automatically 
      - Welcome sessions will not be strictly required for people who already completed training (can continue to use other community events to meet "welcome session" requirement) for 90 days
      - For 90 day period, allow extensions on incomplete checkout from trainings going back to Jan 1, 2022. Trainees who wish to return to complete checkout using the new requirements may contact us to request a new deadline extension during that time.
      - For a 90 day period, trainees with incomplete checkout from events prior to Jan 1, 2022 may request a code to re-take Instructor Training. They may also request an extension if they have been actively engaged in Instructor or Helper roles in the interim.

**Comment by karenword** [comment]
Update: our infrastructure team is going to need a little more time to work on the database changes. All else is on track. New target roll-out date is 24 July.

**Comment by marklcrowe** [comment]
All underway for launch on 24/6/23
