### ISSUE TITLE
Recommendation to Maintainers re PR # 1557

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#260]
## Summary
Proposal to recommend closure of PR #1557 in the Instructor Training Curriculum (link to be added after approval & response), opening an issue to follow up with additional context rather than removing the cited example.

## Background
A pull request to the Instructor Training Curriculum removes "the world is only a few thousand years old" as an example of a misconception that is a fundamental belief, on the basis that this disparages fundamentalist Christians and is not essential to the point. 

Maintainers identified this as an important request that tests the boundaries of inclusivity and risks setting a precedent that may cause harm in other contexts. The Trainer community discussed this issue at meetings on 20 July, 2023, with additional opportunity for async feedback.  

Trainers Leadership has oversight of the Instructor Training Curriculum and effectively plays the role of Curriculum Advisory Committee for Instructor Training materials. Issuing a recommendation on how to handle a proposed change that relates to community values is appropriate to that role. 

This proposal is formulated based on discussion at the 25 July Trainers Leadership meeting and is presented for async voting.

## Implementation
Trainers Leadership recommends the following:
- [x] Opening an issue in the Instructor Training curriculum repository to propose and discuss adding context (e.g. a callout box) addressing the problem that labeling fundamental beliefs as "misconceptions" can feel exclusionary.
- [x] Closing PR #1557, not accepting the proposed change
- [x]  In closing comments:
    1. Thanking the submitter for inspiring a useful conversation in the Trainer community
    2. Linking to Trainer meeting notes on GitHub (requires waiting for these to be posted)
    3. Noting that GitHub issues are the feature we use for things that need discussion before taking action, and this seems to be one of those cases
    4. Linking to the new issue, in case the submitter would like to follow the conversation around added context

## Decision Factors
* Trainers generally agreed that the existing statement was appropriate given the scientific frame of reference of this community
* There was considerable interest in alternative examples. However, if we rule out examples that affect *fewer* people (because this is a problematic basis for change), it becomes difficult to find an example that is realistic as a fundamental belief. 
* Trainers expressed a desire to make adjustments to support inclusion of people who hold beliefs identified as examples of misconceptions. Adding explanation or context of various kinds was proposed as an alternative to removing the example. However, this is not a quick fix - it will take some time to sort out the best way to address this effectively.

### Pros
This course of action results preserves the current state of our curriculum. It avoids tolerating the rejection of knowledge established through scientific processes, a hazardous precedent.
### Cons
This PR identifies a feature of our curriculum that may have negative impact on inclusivity in our community, and this course of action does not provide an immediate solution.

## Possible Alternatives
See Trainer meeting notes for other ideas presented.

**Comment by marklcrowe** [comment]
I like this proposal

**Comment by klbarnes20** [comment]
I have added the notes from that trainer meeting in PR #262.

**Comment by paocorrales** [comment]
I like this proposal

**Comment by annajiat** [comment]
okay

**Comment by ndporter** [comment]
That's either 3 likes and a can live with or 4 likes (not sure what @annajiat meant) so the proposal is approved.
