### ISSUE TITLE
Implementation of Trainer Status Renewal, 2023 (2nd try)

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#261]
## Summary
This new proposal replaces #252, revising plans for 2023 to minimize development of existing processes and redirect effort towards considering automation requests for future years.

## Background
The timeline in #252 is obsolete because this process should follow updates to checkout that have been pushed back. In addition, we have become aware of ongoing planning and development led by The Carpentries Technology Team that will affect future opportunities to automate all or part of the renewal process. If we take time to formulate a detailed request for automation now, this will inform decisions about how to develop our database to best support this process. In addition, other groups are looking at implementing a status renewal process, and planning now will promote alignment in these processes across our subcommunities.

Time investment is a trade-off, and preparing and reviewing form responses to determine acceptability of equivalent activities involved a non-trivial time investment in 2022. We therefore propose reverting to a review-only process in which Trainers who have not met the standards for automated renewal are required to provide information in a Google form, but review of form responses by Leadership and Core Team is focused entirely on formulating requests for automation and all submissions are accepted for renewal purposes in 2023.

## Implementation
2023 renewal process will retain the same criteria for generating automated emails as that used in 2022, with adjustments only to the templates. Trainers who do not receive an automated email confirming their renewal will be required to submit a Google form to renew their active status. Trainers who do not have equivalent activities to report on the form will **not** be required to schedule a meeting to renew their active status as long as they submit the form by the indicated deadline.

Proposed timeline is based on 14 August rollout date for changes to the Instructor Checkout process.
* Review and approve revised form & email templates: 22 August
* Send automated emails to Trainers: 5 September
* Review form responses: 19 September
* Share automation request(s) with Technology Team: 26 September (in addition to background communication as things develop)
* Implement status changes (only for non-responses and alumni status requests): 2 October

## Decision Factors
It would be ideal to pursue both a detailed automation request and a full renewal process, but this is likely to result in both being done less well. 
This proposed process for 2023 differs from that [outlined in our documentation](https://docs.carpentries.org/topic_folders/instructor_training/duties_agreement.html#active-status-renewal-process). However, Leadership has the power to determine when to require a meeting based on reported activities, so it is arguably acceptable for Leadership to determine that meetings will not be required at all as long as that report is made. 

### Pros
A robust automated process is ideal for everyone in the long term. 
### Cons
Trainers who have not been active will be allowed to renew without scheduling a meeting in 2023. This may result in some people being less prepared when they do teach. It may also be perceived as unfair to Trainers who have maintained their active status through volunteer activities.

**Comment by marklcrowe** [comment]
Thanks Karen. As per our Martha's Rules model, I like this proposal.

**Comment by paocorrales** [comment]
I like this proposal

**Comment by ndporter** [comment]
I like this proposal

**Comment by annajiat** [comment]
I like this proposal. Trainers who do not have equivalent activities but are sincerely submitting the form by the indicated deadline, to me are likely to contribute further in various ways in the long term, so that is okay. The benefit of the doubt should go to the trainers.

**Comment by ndporter** [comment]
4 likes and no uncomforables means this is approved.

**Comment by karenword** [comment]
Apologies: I failed to note scheduled leave for Core Team members involved in this schedule. Emails will not be able to be sent until the week of Sept 19. This would allow review during the as-needed meeting on the 26th, with recommendations to the tech team finalized at the 17 October meeting.

**Comment by karenword** [comment]
Apologies: I failed to note scheduled leave for Core Team members involved in this schedule. Emails will not be able to be sent until the week of Sept 19. This would allow review at the 17th of October (UTC) meeting, with recommendations to the tech team finalized the following week (optionally using the as-needed meeting that week for further discussion).

**Comment by ragamouf** [comment]
@annajiat and @ndporter As members of TLC last year, I appreciate your familiarity with this issue, and ask that you submit a proposed new timetable for the 2024 Trainer renewal process.

**Comment by sheraaronhurt** [comment]
Hello everyone. I am looking into rolling out renewal status with Trainers/Instructors simultaneously. Once a date is set, I will bring to the TLC.

**Comment by ragamouf** [comment]
From TLC meeting 2024-05-10, Core Team won't get to this before Q3 2024. This satisfies my request for a timeline. 
To progress this to resolution, the next step is for the Trainers Leadership Committee to start a draft rubric document.  
@annajiat and @ndporter, as previous supporters on this issue, are you able to begin action and share a status update at the next TLC meeting in June 2024-06-14? Please let me know promptly if you can't, so I can offer it to others in the TLC.

**Comment by ragamouf** [comment]
This issue is moot since Core Team are incorporating trainer renewal within a broader suite of automating other volunteer renewal processes.
