### ISSUE TITLE
Change election schedule and offer 2nd year without re-election for incumbents

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#271]
## Summary
Propose to update lanuage in Governance.md describing election schedule and term limits

## Background
- The first Trainer meeting of the year is typically held in late January, and the holiday pause can mean an extended break between pre/post discussion meetings. This proposal moves elections to February, reserving the January meeting for pre/post discussions.
- Currently, there is no means to stagger participation for Leadership members, such that there is always someone with experience on the committee. That has not yet been a problem yet, as incumbent members are often elected. However, standing for election takes work, and if we want incumbents to remain, that effort would be more productively focused on supporting elections in other ways.

## Implementation
#270 
## Decision Factors
Because this does not affect the terms under which Trainers retain Active status, it can be approved by Leadership. However, any Trainer may request that this proposal be submitted to the community for ratification in the next election.

### Pros
This update resolves the problems cited in "background" above

### Cons
Trainers may wish to review the service of every panel member and have a vote on all of them each year. Trainers may feel more connected to and invested in Leadership through election-related communications each year.

## Possible Alternatives
The election schedule could be changed without adjusting term limits. 
Incumbents could have additional community reporting requirements if they choose to remain (e.g. responding to election prompts even though they are not on the ballot.)

**Comment by ndporter** [comment]
@carpentries/trainers-leadership I believe this is ok to close, as it's been discussed and tabled for now.

**Comment by jonathanwheeler01** [comment]
Going to close, but adding a link for reference to the relevant meeting minutes:

[2023-11-28 Leadership minutes](https://github.com/carpentries/trainers/blob/main/leadership_minutes/2023/2023-11-28-leadership-minutes.md#elections)
