### ISSUE TITLE
Consolidate two pages on becoming instructor

### ISSUE THREAD

**Issue by ndporter** [carpentries/trainers#292]
## Summary
Currently, there are 2 close, but not identical descriptions of the process of becoming an instructor, each linked from different places and potentially different maintainers:
- https://carpentries.org/become-instructor/
- https://docs.carpentries.org/topic_folders/for_instructors/new_instructors.html#steps-to-becoming-an-instructor

Duplication like this increases the likelihood of confusion and of missed changes (for example, the Handbook describes application for open instructor training while the carpentries.org page does not).

## Implementation
My recommendation, unless there is a formal policy reason to keep the Handbook page, is to (1) remove the Handbook page and (2) redirect any links to the other page, as well as checking that useful materials on the handbook page such as
> Read more about Instructor motivations in Dr. Beth Duckles’s report, [Value of Software Carpentry to Instructors](https://software-carpentry.org/files/bib/duckles-instructor-engagement-2016.pdf).
 are represented elsewhere.

## Decision Factors
- What are the current purposes/functions of the pages?
- Is there an intended use case difference?

### Pros
- Reduce potential for confusion
- Reduce burden for site maintainers

### Cons
- Time to update/remove
- May be necessary

## Possible Alternatives
Alternatively, if maintaining both is important due to policy or audiences, I recommend clearly differentiating the purposes of each page, likely such that new potential instructors are directed through carpentries.org and the handbook remains as a more formal record of requirements/policies for leadership, trainers, etc.

Otherwise, the alternative would be to keep the structure as is, but delegate someone to verify all information on both is current and accurate.

**Comment by ndporter** [comment]
@sheraaronhurt or @maneesha can you confirm if there's a formal policy reason to keep the handbook page or have these separate? It seems like there's more actual policy in the other version anyway, but I want to ensure we don't overstep our bounds.

If core team confims they don't have an issue consolidating I like this and vote yes per Martha's rules.

**Comment by jonathanwheeler01** [comment]
I also like this proposal and vote yes with the same caveats as @ndporter. It seems that the handbook page has a little more detail about the internal processes for reviewing instructors, so maybe an alternative would be to change the heading of that section?

**Comment by ragamouf** [comment]
I think a better alternative is to confirm what created the discrepancies in the first place? I wonder if it's not a communication issue for Core Team - ie, ensuring website content matches what is written in the handbook. 

It's important to have a public facing page for the website for prospective instructors, and I appreciate the role of the handbook to cover the rules and policies applied to the process. But they should not contradict each other.

@sheraaronhurt and @OscarSiba what do you think?

**Comment by maneesha** [comment]
We are in the middle of a large overhaul of our websites and handbook.  We should deprecate the page on The Carpentries website and keep the page in the handbook.

**Comment by annajiat** [comment]
I agree with @maneesha

**Comment by ragamouf** [comment]
This issue is moot given the website and handbook upgrade. Agreed at TLC meeting 15 Nov 2024.
