### ISSUE TITLE
Define a process for leadership committee members to close outstanding issues

### ISSUE THREAD

**Issue by jonathanwheeler01** [carpentries/trainers#295]
## Summary

The Carpentries uses GitHub issues and pull requests to manage distributed workflows for committee business including approval of minutes, proposals, and topical discussions. This practice facilitates collective decision making and provides the community with transparency about committee operations. Some issues or discussions can continue over long periods of time, but may eventually become dormant. Dormant issues may actually have been resolved through policy or process changes, while discussion of other issues can carry on for a time before eventually tapering off without any definitive action or change occurring. A third category of issues may include topics which merit periodic discussion and review, for example privacy.

The Carpentries lesson maintainers have a clear process for closing issues through pull requests. Some issues in this repository, including many that relate to leadership committee operations, do not require a pull request. In such cases, there is no established process for closing or archiving issues, which can make it difficult to assess which issues need additional or renewed attention. This proposal seeks to address questions about closing dormant issues in GitHub.

## Background

In addition to the information provided in the summary, it is noted that the leadership committee uses Martha's Rules to put forward proposals. It is unclear whether closing dormant issues requires a full proposal and discussion, per Martha's rules, for each issue. That seems like it would create a lot of additional overhead and administration. However, before closing an old issue it may be necessary or useful to create a new proposal based on that issue. For example, an annual review of privacy policies and practices may be a topic worth periodic consideration and discussion.

## Implementation

If allowable based on [committee roles and defined powers](https://github.com/carpentries/trainers/blob/main/powers_responsibilities.md), I recommend documenting a process through which leadership committee members can close outstanding issues:

1. Verify that issue is at least a year old, with no action or discussion within the past year.
2. Add the *Ready for archive* tag to the issue.
3. Assign the current leadership committee to the issue.
4. Add a comment proposing to close the issue.
5. Notify the leadership committee via Slack.
6. After one week, if no concerns or questions are raised, close the issue.

### Pros

- Clear guidelines for managing committee workflows in GitHub.
- Clarify and establish priority issues and topics.
- Identify topics that merit periodic review.
- Closed issues are still available (and public) in GitHub.

### Cons

- Closed issues will be harder to locate and review.
- Some important topics and discussions may become de-prioritized.
- Negative impact on transparent governance.
- May actually create work where an ad hoc process can be as efficient.

## Possible Alternatives

1. Continue without an established process and close issues in an ad hoc way.
2. Use pull requests to close all issues, similar to the process used by the maintainers.
3. Convert outstanding issues to discussions.

**Comment by ndporter** [comment]
I think this is a great balance and vote yes per Martha's rules.

**Comment by ragamouf** [comment]
thanks Jonathan, I think this will provide much needed clarity on collaboration. I vote yes, I support this idea.

**Comment by annajiat** [comment]
I vote yes with a proposal for a new tag which can help in keep track of issues that were closed due to dormancy so that it becomes easier should anyone like to review.

**Comment by ragamouf** [comment]
Following discussion at TLC meeting 14/15 Nov 2024, consensus to add a "Dormant" tag if "Ready to archive" doesn't prompt action.
