### ISSUE TITLE
Default branch changed to main?

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#45]
Can this repo be updated.  There are no active PRs right now, so it's a good time. 

@fmichonneau

**Comment by karenword** [comment]
Looks like this is done!

**Comment by brownsarahm** [comment]
this repo still shows master for me?

**Comment by karenword** [comment]
Whoops! Working too fast this morning. Reopening!

**Comment by fmichonneau** [comment]
done! sorry for the delay. I updated the base branch for the open pull requests.
