### ISSUE TITLE
Which voting system should we use?

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#48]
The Carpentries uses the ElectionBuddy platform to host community elections. However, multiple options exist for how such elections may be organized.

One favored suggestion so far has been a [Single Transferable Vote](https://electionbuddy.com/features/voting-systems) system, in which ranking is used to transfer votes and select the most-favored candidates for a panel. 

All available voting systems on ElectionBuddy are identified here: https://electionbuddy.com/features/voting-systems

**Comment by brownsarahm** [comment]
EC uses first past the post

**Comment by dvanic** [comment]
Please don't use first past the post! This can turn into a deeply philosophical debate, but preferential voting really does allow a particular individual's votes to be counted in a more balanced manner (although, yes, it's unfamiliar in many countries and takes a bit more to wrap one's head around than FPTP).

**Comment by Denubis** [comment]
I would like to very much push for STV voting here. I also would like to suggest some sort of primary process so that people don't need to rank 30+ people in the final election. The only problem with a primary is that we have no useful infrastructure for it or looking at a summary of contributions or people's reactions to those contributions.

Thus I propose:
1. We use STV or (some sort of ranked-choice)
2. We cap the people in the final election to 10-15 through some sort of primary using Approval Voting (https://electionbuddy.com/features/voting-systems/approval-voting)

**Comment by jcoliver** [comment]
With STV, does one need rank _all_ candidates?

**Comment by Denubis** [comment]
@jcoliver "The quota can change if a vote is “exhausted”. A vote becomes exhausted in the event that the voter has not indicated a different candidate to transfer their vote to, or all of their other indicated candidates have already been eliminated. " -- Suggests the answer is "yes"

**Comment by jcoliver** [comment]
@Denubis , then perhaps we could skip the primary / pre-approval step if STV is used and just ask trainers to rank as many (or a maximum) of all candidates.

**Comment by Denubis** [comment]
@jcoliver trying to do an STV for 30+ people is a tough ask. It also means that nominations can be far more lightweight if we know that we have a "second round of asking questions and providing details about contributions" But maybe we should note that if we don't have that many, we can skip primaries.

**Comment by dvanic** [comment]
I think that up to 50 STV can work (I mean, we don't have _that_ many trainers) - so we can specify in the docs that up to X nominations we use a single STV round, while with more that X people nominated we do two rounds.

**Comment by brownsarahm** [comment]
I agree STV is a good idea, (I was just recording FPTP above because it was a question in the morning meeting)

maybe we can say if there are more than 15? candidates we do a primary process to reduce down to that point.  

What would you imaging the primary looks like?

**Comment by Denubis** [comment]
@dvanic suggested a STV run for the primary. Perhaps approval voting to the STV threshold would also work. The main thing I want to optimise for is time-spent-on-application. 

For primary or "before we accept you as a final person" a paragraph on themselves, a pargraph on their "platform" (goals, m.o. wahtever), and a paragraph on their specific contributions to the carpentries with a link to their github so people can see their comments and contributions seems more than sufficient.

For example, I would (were I to apply) link:
https://github.com/search?q=is%3Aissue+commenter%3Adenubis 
and 
https://github.com/Denubis?tab=overview&from=2020-10-01&to=2020-10-31

That seems more than enough work for some set of people (coordinators, community) to say "Yeah, you can participate in the election.")

**Comment by karenword** [comment]
I could be wrong, but I think that the risk of having 30+ candidates for these elections is quite low. 

@Denubis your last comment might be better suited to address https://github.com/carpentries/trainers/issues/49 ?

**Comment by Denubis** [comment]
Fair enough, I'll copy it over there.

**Comment by zpainter** [comment]
I am also here to support something other than FPTP. Don't have any other comments besides that.

**Comment by ragamouf** [comment]
Similar to Zac, I'm here to support single transferable vote, as an alternative to first past the post.

**Comment by mpfl** [comment]
I would like to support a preferential ballot (as I am familiar with it) or single transferable vote (because it looks like something I am familiar with).

First past the post is an awful method of voting.
