### ISSUE TITLE
How should nominations work?

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#49]
A self-nomination process should present a low barrier to entry. It should also offer voters useful information in evaluating candidates.

As an example, The Carpentries Executive Council uses [this form](https://forms.gle/qicdVUqqTWtQ8mHT6) to collect self-nominations for community-elected positions. Form entries are used to publish a blog post, and candidates may choose to submit a video.

**Comment by Denubis** [comment]
(Migrated from #48)

For primary or "before we accept you as a final person" a paragraph on themselves, a pargraph on their "platform" (goals, m.o. wahtever), and a paragraph on their specific contributions to the carpentries with a link to their github so people can see their comments and contributions seems more than sufficient.

For example, I would (were I to apply) link:
* https://github.com/search?q=is%3Aissue+commenter%3Adenubis
* https://github.com/Denubis?tab=overview&from=2020-10-01&to=2020-10-31
* In slack, encourage people to run from:@Brian Ballsun-Stanton
* In topicbox (good grief we have a lot of these): https://carpentries.topicbox.com/search:from%3A%22Brian%20Ballsun-Stanton%22

And probably other bits that I've forgotten we're using. That way, people can do due diligence on my public participation, and have a sense of my intentions.
That seems more than enough work for some set of people (coordinators, community) to say "Yeah, you can participate in the election.")

The trick is that we're not asking for a heavy time investment, but allow people to accurately characterise community involvement and pragmatic leadership.

**Comment by karenword** [comment]
Since this suggestion hasn't attracted comments, it's not clear to me whether we have agreement on using search links to evaluate contributions. I am concerned that there are SO many ways of participating that even this seemingly comprehensive strategy will only capture participation unevenly and potentially unfairly. 

I've created a [template form](https://docs.google.com/forms/d/1hokNixEPDRSGfY0x2OwQMaitt-QRgJNhibHza1Ff1ps/edit?usp=sharing) that asks nominees to describe their contributions, goals, and stand on relevant upcoming issues. I took the liberty of proposing a fairly specific question on this last point. We can revise this, including potentially adding a field that requests platform usernames (or anything else) after more feedback or discussion on this topic.

**Comment by Denubis** [comment]
Perhaps we can ask for citations? 

```
In the coming year, this panel will address many issues. These include but are not limited to: completing governance construction, revisiting the Trainer Agreement, and developing policy around sponsorship of Instructor Training seats and events. Please indicate how you plan to go about addressing issues like these, either broadly or specifically. What can Trainers expect from you as you engage in making decisions on these and other subjects?
```

Is too big a question. I propose splitting it into:

Section:
In the coming year, this panel will address many issues. These include but are not limited to: completing governance construction, revisiting the Trainer Agreement, and developing policy around sponsorship of Instructor Training seats and events. The following questions will discuss this context.

Question 1:
Please discuss how you have engaged with the trainer community around questions of governance and policy. Where possible, provide links to conversations which highlight your approach.

Question 2:
What can trainers expect from your leadership as you engage in making decisions and representing the trainer community on policy, governance, and leadership topics?
