### ISSUE TITLE
Items to defer for determination by the elected committee

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#50]
Some decisions about how governance should work may not be necessary or appropriate to determine until an elected group is in place. A few suggested issues that are important to consider but may be deferred are:

- Arrangement of liaisons to other groups (EC, Maintainers, etc.) 
- Identification of needs for privacy in specific documentation or communications channels
- Balance of synchronous and asynchronous participation mechanisms to meet the needs of a globally distributed committee
- Many of the procedural details outlined in [The Carpentries Committee Policy](https://docs.carpentries.org/topic_folders/governance/committee-policy.html)

**Comment by karenword** [comment]
Per @brownsarahm : One of the first things that the new leadership committee will do is to create a policy on policies where it scopes out what needs to be policy and what the procedure for changing policies is. 
Likely EC should maintain a carpentries wide policy-on-policies
Would need a trainer-specific scope of what actions must be policy vs what are more general actions.
Possibly add a specific 
Trainer agreement document should include the process for ratifying the agreement.

**Comment by karenword** [comment]
Among the items that may demand additional policy: detailed communications and notification procedures to ensure that Trainers' voice is invited and respected while Leadership also retains authority to act efficiently.

**Comment by brownsarahm** [comment]
@karenword Can you ask EC again about policy on policy? if we can adopt one from them or should draft our own?

**Comment by jonathanwheeler01** [comment]
Reviewing this issue for possible closure and archiving. Some of the issues, documentation, and policy discussed have been published at 

- [Powers and responsibilities](https://github.com/carpentries/trainers/blob/main/powers_responsibilities.md)
- [Governance](https://github.com/carpentries/trainers/blob/main/governance.md)

There doesn't seem to be a single policy on policies, but the linked Powers and Responsibilities page addresses some policy issues. 

Some other issues - liaisons, privacy, etc. - may be worth a periodic or annual review. But at this time I propose we close this issue.

**Comment by ragamouf** [comment]
I agree, this is ready for archive
