### ISSUE TITLE
How should removal work?

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#51]
The current document includes no mechanism by which elected members may be removed prior to the end of their term. Removal mechanisms may offer authority to the committee, the Trainer community, or both.

The Carpentries Executive Council grants removal authority to the Council [here](https://docs.carpentries.org/topic_folders/governance/bylaws.html#removal).

**Comment by zpainter** [comment]
What other mechanisms of removal exist in other Carpentries communities? If there are none suitable, perhaps this needs to be a larger discussion for the rest of the organization?

**Comment by karenword** [comment]
Lex indicated that they chose not to include a "nuclear option" in The Carpentries bylaws to withdraw the Executive Council. However, this is a smaller community that arguably has more at stake in leadership decisions, so it's possible that a different choice would be suitable here.

**Comment by Denubis** [comment]
75% of currently active people, maybe?

**Comment by karenword** [comment]
If a community removal mechanism is preferred, I'll note that the criterion for changing the bylaws currently specifies both quorum and % voters in favor. 75% in favor implies minimum 75% quorum which is more stringent (potentially appropriate here).

I'll be merging PRs today in preparation before requesting comment from the EC, and the current PR mirrors the EC policy. I'll un-link this issue so we can continue discussion on this question of community removal.
