### ISSUE TITLE
Core team and leadership

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#52]
should it be stated here or is that inherited from the carpentries commitee policy that core team members don't stand for election?

**Comment by karenword** [comment]
Also, should core team members even be eligible to vote? They have voted on things in the past.

**Comment by brownsarahm** [comment]
The above was a question to be true to what happened in the meeting.  My vote is for this being an EC decision that's applied elsewhere.

**Comment by karenword** [comment]
I agree it may go without saying that Core Team members cannot run for election. However I think we may need to be explicit if Core Team members are not eligible to vote, since this is a change from the status quo for this sub-community.

**Comment by karenword** [comment]
Also: I think Core Team members probably should not be allowed to vote.

**Comment by Denubis** [comment]
Why? If there are trainers in the core team -- they can vote. I don't think core should have any special privileges, but the "trainer in good standing" is strict and general? (I think you're the only one who fits those criteria and I certainly don't want to disenfranchise you)

**Comment by brownsarahm** [comment]
I think most core team members are trainers, they fill in when a trainer can't be found to teach a workshop. I know for sure that the following are trainers
- Kari
- Francios
- Toby
- Sher
- Kelly (possibly not yet taught through)
- Maneesha
- Karen
- Angelique (maybe not core team?)
- Erin

**Comment by ACharbonneau** [comment]
I think it sort of depends on the size of the trainer pool, and how many of them typically participate in voting. If turnout is typically low, then having the core team vote probably is roughly equivalent to just having the core team appoint the committee.

**Comment by karenword** [comment]
I expect turnout to be strong enough that Core Team will not be functionally appointing anybody. However, they may be key to achieving quorum or a simple majority. Core Team votes may have been key to approving the recent Trainer Agreement, for example. I don't think that's a good thing. 

There are points at which there will be -- and should be -- a tension between the needs of the organization and the needs of the community. This is one of the key reasons why we need a community governance group: to provide a clear voice for the community that can counterbalance power held by the Core Team that will tend to favor policies that are good for the organization. Core Team members have plenty of power if they want to see policies changed. I think that this group will best represent the community if their election is determined without the input of Core Team members.

**Comment by karenword** [comment]
Also: to add to @brownsarahm 's list, Serah and Zhian have recently joined us. So, this is not a small number of votes!

**Comment by Denubis** [comment]
That seems persuasive. I support this change.

**Comment by ChristinaLK** [comment]
I like leaving the core team off for now - if we want to have the core team be able to vote later, logistically it's much easier to vote to add their votes than to try to remove them.
