### ISSUE TITLE
How should decisions about the checkout process be made?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/trainers#53]
The Powers and Responsibilities (P&R) document doesn't explicitly define who would have power and responsibility to make changes to the requirements for Instructor Training checkout:

- does this fall inside changes to the Instructor Training curriculum i.e. would P&R for making/overseeing changes to checkout process include P&R to change the checkout process?
- if not, how should powers and responsibilities for the checkout process be distributed?

**Comment by karenword** [comment]
Looking at documentation alone, this falls within the domain of Instructor Training curriculum. Our repository is the only place, other than email templates, where requirements are detailed. The EC may have an opinion on this, but I think we should submit that approving changes to checkout is a power of Trainers Leadership.
