### ISSUE TITLE
Quorum for changes to the governance document

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#54]
_this is in reference to the last section ([Ratification and Governance](https://github.com/carpentries/trainers/blob/master/governance.md#ratification-and-governance)) of the governance document, the current text is:_
> A proposal is adopted with a quorum of 2/3 trainers in good standing voting (for,against, or abstain) and a simple majority of the votes in favor.

2/3 of in good standing may not be a good threshold bc in good standing doesn't drop people off after any amount of inactive time and we don't want inactive people to count against achieving quorum (even if we do want them to be allowed to stand for election upon return) 

Probably should be "active" but that's not very well defined, so we need to think about that a little?

maybe we use "responded to the last trainer agreement request" as a threshold for being required. 

What threshold was used to ratify the trainer agreement?

**Comment by karenword** [comment]
We used a simple majority of active Trainers for ratification. However that won't work for a panel election. Functionally, that sort of served as a 50% quorum as most votes were in favor.

If we continue to inactivate people for non-response to annual commitment, I think 50% is realistic for quorum and 2/3 might be achievable but not for sure.

**Comment by zpainter** [comment]
Changes should be difficult, but not impossible. 3/5ths might be a decent compromise in either event; as it shows a clear majority without being overly onerous.

**Comment by ChristinaLK** [comment]
I think the challenge here is to determine the size of the denominator. Then it might become easier to determine what the numerator should be. 

I like @brownsarahm 's idea of "responded to the last trainer agreement request" as the denominator b/c that's an empirical(ish) measure of who would actually respond/vote. Then I think 2/3 or 3/5 is reasonable. I'd like to get a sense of real numbers (for example, how many people *did* respond to the last trainer agreement request?) to figure out how I feel between those two values.

**Comment by karenword** [comment]
54 out of 83 people voted on the Trainer agreement. Subtracting core team members, that would have been 46 out of 83.

Several folks who didn't vote have since become inactive. If we consider this to be a minimum level of participation (given that many were somewhat ambivalent about the agreement), I think 3/5 is probably achievable and 2/3 could require some hustling.

**Comment by brownsarahm** [comment]
If we remove core team from voting, I think we should remove them from the denominator as well, so then it would be 46/75, which is  above 60%. 

So: active trainers, who are not core team members are eligible voters and 60% of eligible voters must vote for it the vote to be valid.  

Then do we want to keep simple majority of that for changes to be accepted?  That would mean that only 30% of the community needs to approve for something for it to go into effect.  If we're going with 60% quorum, I think maybe we should require higher approval for something to pass, maybe go up to 75% must vote yes to approve?
