### ISSUE TITLE
Proposal to have only one Instructor training lesson material repository

### ISSUE THREAD

**Issue by dpshelio** [carpentries/trainers#73]
At the moment there are two repositories for the instructor training, an ["official one" under the carpentries organisation](https://carpentries.github.io/instructor-training/) (official) and [another for major (content/structure) updates](https://github.com/data-lessons/instructor-training) (sandbox).

The sandbox has been used as a temporary place to incorporate and tests some changes, but it has become a place where some important topics are being discussed (e.g., data-lessons/instructor-training#18). 

I'd prefer to have all this in the same repository and here are some reasons why:

1. Having two repository means that a person who wants to contribute has to look into two places to see whether a topic has been already addressed (besides slack, etherpads and mailing lists).

2. This can produce some misunderstanding of what is "developed" in the open and what not - even when the sandbox is open and it's labelled as such on the repository description, though a bigger notice in the README would make it clearer.
  For example, if a trainer is unaware of the sandbox and suddenly see a major structural change that goes with not much review because it's been reviewed thoroughly already somewhere else could create some kind of "separatism" feeling.

3. Technically, the two repositories may diverge so an then with fixes that happen in one and not in the other. This could make history a bit messy producing more work for the maintainers.

I believe the sandbox repository was originally created to simplify the process of reviewing changes and maintenance. For example to visualise the lesson changes on github pages and to produce large changes. For these cases now there are some new tooling/features around github that could make that work easier.

1. Rendering of contributions. This is offered on some of the carpentry lessons via netlify. There are other ways, like using Circle-CI which I use with other jekyll pages to not only create a "preview" but to run other checks as accessibility and links proofer. 

2. Large changes (content/structure) could be done via a parallel branch instead of at a different fork. That parallel branch should be only created by a lesson maintainer but allowing anyone to create PRs to that branch. A draft PR could be created from that parallel branch to the official gh-pages that will show the preview of any PRs merged to it.

3. Using labels and project boards we can ease the browsing of the issues and contributions to the repository while having all the discussion under the same "roof".

**Comment by brownsarahm** [comment]
For a little bit of added clarity/ to ease concerns.  
__concern 2:__  all trainers will be invited to comment and there will  piloting and onboarding to the new revision before it is merged t the main repo.  This process, comment, piloting and onboarding should be kept for all major revisions, I think, even if they move to stay within the main repository. 

__concern 1,3:__The sandbox is not currently used for regular maintenance, only for major revisions are taking place and the issues being addressed are all based on issues in the main repo. The maintainers are noting on relevant issues in the main repo when they're addressed in the sandbox. 


That said, for the next major revision, a revision branch that's rendered might be sufficient and will certainly be considered.  We can also make sure that we have some notes for maintainence here.  For this revision, we relied on core team memory for how past revisions worked and a written guideline would both make the process simpler for maintainers and community, but is subject to reviewing all the reasons maintainers settled on continues use of the sandbox.

**Comment by ChristinaLK** [comment]
I think you summed it up well @brownsarahm ! 

@dpshelio, I think the main gap here was between people with the expertise that could allow us to render a development branch and the maintainers wanting to move forward with the next big release. A good next step might be to determine who (either in the Carpentries core team or community) has the needed git/gh-pages expertise and the time to make it happen.

**Comment by brownsarahm** [comment]
this is closed by #82
