### ISSUE TITLE
Use issue templates and discussions to manage conversations

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#75]
## Summary

To sort and structure discussion among trainers and facilitate transparent, I propose to add issue templates for proposals and RFCs to this repo and activate discussions. After activating discussions, I propose we move discussions that are current issues from the IT repo to the discussions tab here. 

## Background

The meeting rules under consideration suggests using issues in this repository for items for the leadership panel to consider (as this issue). 

Currently, the IT repo has a large number of discussions that are items that need a decision beyond the typical scope of the maintainers and some that are not directly actionable for the curriculum. 

Github has a new feature called [discussions](https://docs.github.com/en/discussions) that can be activated to create a separate space from issues to discuss matters. 

### Pros

- structured proposals will be faster to review and more likely to be complete
- having the template auto filled using the GH issue template feature
- moving discussions to the discussions tab will help clarify the maintainence load on the IT repo and this repo. 
- if a topic is opened on the wrong forum, maintainers can [tranfer issues](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) between IT repo an this repo and [convert from issues to discussions](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion)
- moving more nuanced, tentative discussions here instead of on the IT repo where trainees sometimes follow could streamline thing and reduce the confusion for trainees
- discussions could be a good place to facilitate asynchronous engagement

### Cons

- templates add a step when issues are created
- having more places to look could make it harder for people to find information

## Possible Alternatives

- Include templates in the meeting rules document
- Let proposals be added without uniform structure

## Appendices

This section is preliminary examples of the templates, if the proposal is accepted, these will form the beginning of the pull request to add them.  The final text will be approved by the leadership panel with asynchronously via pull request. 

### Template for Proposals
```
---
layout: default
name: Template for Proposals
about: Adding a new proposal for discussion at the next leadership meeting
title: a one sentence summary of the proposal
labels: proposal
assignees: 
---

## Summary

## Background

## Decision Factors

### Pros

### Cons


## Possible Alternatives

<!-- ## Appendices
 (optional, uncomment line above if needed -->
```

### Template for Request For Comment

This is pretty tentative; I expect that we will iterate some on how we want these structured. 
```
---
layout: default
name: Template for Requests for Comment (RCF)
about: RFCs are for broad discussions within the trainer community 
title: a description of the topic and deadline for commenting
labels: 'request for comment'
assignees: 
---
## Summary

## Timeline


```

**Comment by jcoliver** [comment]
I think this is a great idea; having structured templates can be a very effective means of managing expectations. My few cents:

+ Could we include a brief guide for use? Perhaps in the templates themselves (like the templates on Carpentry repo PRs). These would explain when to use the Proposal template, when to use the RFC template, and when to use a vanilla Issue.
+ How about spelling out what RFC means? :)
+ Will such discussions ever be "Closed"? Could we have a rough outline of when/why a discussion would be closed?

**Comment by ACharbonneau** [comment]
## Templates

> * Could we include a brief guide for use? Perhaps in the templates themselves (like the templates on Carpentry repo PRs). These would explain when to use the Proposal template, when to use the RFC template, and when to use a vanilla Issue.

issue templates are mostly magic for the user. We/some admin sets them up in the repo in a hidden folder, and when the user clicks new issue, it shows them a page like this (this is from one of my non carpentries projects):
![image](https://user-images.githubusercontent.com/1719360/111683794-51464480-87fc-11eb-9ed9-d2ec7ce43389.png)

So, you can embed the 'what is this issue for' explanation in the template itself. If I click on one of these I get:

![image](https://user-images.githubusercontent.com/1719360/111684050-99656700-87fc-11eb-8edf-b13a7961476b.png)

so it gives pre-filled text, and you can pre-fill the title, pre-assign labels or milestones or whatever to be attached to issues made with different templates. 

To add that fun stuff, we would basically add some meta-data to Sarahs proposed template, which you do with yaml headers. So something like:

```
---
layout: default
name: Template for Proposals
about: Adding a new proposal for discussion at the next meeting
title: Proposal Title
labels: proposal
assignees: 
---

<!-- include a one sentence summary in the title of the issue>
## Summary

## Background

## Decision Factors

### Pros

### Cons

## Possible Alternatives

<!-- ## Appendices
 (optional, uncomment line above if needed -->

```

If anyone hasn't played with templated issues before, the repo I'm screenshoting is open, and it's safe to go poke it: https://github.com/nih-cfde/use-case-library-build/issues just click 'new issue'

---

## Discussions

I've also got a new but reasonably active discussions board in an open repo if anyone wants to see a working example: https://github.com/nih-cfde/published-documentation/discussions

They have the feel of issues, but they're really much more like a slack overflow type service. So they don't really close, discussion threads just move further down as they become less relevant. 

They're neat tho, you can customize the categories, and do sorting and linking. It even has a mini-community contributing feature.

**Comment by brownsarahm** [comment]
I updated the initial comment to incorporate the metadata and expand RFC. 

I think we should indicate when/why an issue will be closed should be in #74 . 

For "discussions", I think we would just mark things answered if they're "closed" but that the idea would be to put things there when they're topics that don't have a clear plan for closure.  There are some issues in the IT repo currently that are collecting ideas or sharing tips that we don't really know where to put them.  I think that the discussions would be a better place than creating a whole new wiki/discussion board.

**Comment by karenword** [comment]
FYI I enabled Discussions in the Instructor Training sandbox repo, so if you were feeling shy about playing with Amanda's repos, you can really poke around here because that's what this repo is for: https://github.com/data-lessons/instructor-training

So far, migrating an Issue to a Discussion caused my browser to freeze in an endless migration loop, but I managed to get out of it by closing the tab and opening it in a new window.

**Comment by brownsarahm** [comment]
Here's an example issue that was converted to a discussion. https://github.com/data-lessons/instructor-training/issues/51

**Comment by karenword** [comment]
In our maintenance meeting last week, we talked about whether/when discussions should live on the IT curriculum repo vs this repo. Since these discussions are often tentative, I can see where it may be easier to hash these out frankly in the more secluded corners of this repo, and I suppose that if we want certain discussions to remain fully public we can simply leave them as Issues in the curriculum repo. So, I think this structure will work well. I'll point out that this is also relevant to the broader question of what should be public vs private, overall, with this repo being a sort of middle ground in that it is public but not well traveled.

**Comment by ACharbonneau** [comment]
If you want occasional private discussions you can tie them to teams. I can demo it if you want

**Comment by brownsarahm** [comment]
@karenword can you figure out what Core Team member can turn on discussions on this repo?

**Comment by karenword** [comment]
Now *that* is something that I actually can do. Done!
