### ISSUE TITLE
Timeline for trainer agreement update, ratification, and renewal

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#77]
## Summary

A proposal for the timeline and outline of the process for the trainer agreement renewal. 

1. Leadership panel finalizes a trainer agreement update process at May leadership meeting
2. Preview trainer agreement update process in trainer meetings in June
3. Open content discussion at July trainer meeting of draft new agreement 
3. Share agreement as is ready for rattification at July 3rd week meeting or August 1st week meeting. 
4. trainers ratify the agreement in August
5. trainers complete renewal in September
6. Core team uses information from renewal while scheduling Q1 2022 IT workshops
7. New agreement goes into effect in January 2022.

The process that's still to be decided is how updates will be accepted from the community, how the leadership panel will respond.  This process may result in updates to the timeline above, but I'm proposing this process now, to make it clear how many steps are in the process and what the overall time line is. This is also a chance to make sure that we are open about what is coming and that we can update. 

We can either accept this proposal or iterate on it to incorporate the process directly before accepting.  Once we have clarity on the governance matters from the EC we may make this a policy that, but we may not have time to plan this out before the Core team needs information for planning purposes. 

## Background

the 2020 renewal process attempted to create more flexibility for trainers but the process and the context of the agreement concerned many trainers, so I propose that we have a more open process around the the updates to the agreement

### Pros

- this timeline follows works backward from the core team need to schedule and leaves some time to get things ready for meetings
- keeping the whole process open is in alignment with values

### Cons

- it may not make sense to separate this proposal from the actual process of how much time we want to open discussion
- there may not be enough time from showing content in July 

## Possible Alternatives

there are many possible shifts of the early dates and including the number of steps and points for feedback

**Comment by karenword** [comment]
I would like to suggest the following updates to this timeline:

4. Share agreement that is ready for ratification at November 18 meeting 
5. Trainers ratify the agreement in January (concurrent with Leadership elections)
6. Further discussion with community to determine best time of year for renewal to commence/repeat.
