### ISSUE TITLE
Remove Policy from the IT curriculum to simplify maintainance

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#78]
_This is posted as a starting point for discussion in a leadership panel meeting and in the spirit of full transparency, all are welcome to comment or request that it go to a trainer meeting_

## Summary

As much as possible, policy should be maintained outside of IT curriculum episodes. Episodes should  instead contain questions for facilitating trainees to examine the policy in its source location rather than restating the content of policy.  For most policy, its home will be the [Carpentries Handbook](https://docs.carpentries.org/). For trainee facing policy that the  Trainer community to should retain ownership of would be maintained on the supplemental pages in the IT repo. 

> For example, the checkout guidelines are currently duplicated on an extras page and an episode. We could decide that the policy-content would live on the [extras/Checkout Procedure](https://carpentries.github.io/instructor-training/checkout/index.html) page and the [Checkout Process episode](https://carpentries.github.io/instructor-training/20-checkout/index.html) would include exercises for how to find that material and possibly the motivation for the checkout process. 

If there is material that the community agrees should be maintained in multiple places, all locations should contain a comment (that need not render) that indicates the other places. Based on responsibility for the content, one should be deemed the 'primary source' and other locations will be considered 'secondary coverage'. The comment in the primary source should remind  the owner to create issues or PRs to flag that updates are needed in the other locations.  The comments in secondary coverage locations should indicate the primary source and indicate which group is responsible for that content. 

> For example, it makes sense to include a summary of the pre-workshop preparation steps in the e-mail trainees receive.  
> The primary source will be the [IT/setup page](https://carpentries.github.io/instructor-training/setup.html) and the [handbook/one week trainee e-mail](https://docs.carpentries.org/topic_folders/instructor_training/email_templates_admin.html#one-week-trainee-email-online-training) would be secondary coverage. 

### Implementation Steps

- Panel should decide reject, approve, or discuss with trainers
- if discuss, choose  RFC or trainer meeting topic 
- once trainers (or panel ) approves, implementation will require coordination with EC and broader Core team how to make this "official" since we're requesting that others notify the IT maintainers of policy changes in a specific way
- someone needs to make an initial pass at updating the IT curriculum and handbook to this effect:
    - update checkout episode
    - updates for how we operate
    - review and flag other places?
    - add in [01-welcome](https://github.com/carpentries/instructor-training/blob/gh-pages/_episodes/01-welcome.md#the-carpentries-history-and-culture) that we'll be using the handbook throughout as a reference that will always be there for trainees (this could also help proactively ease concerns about too many links) 

## Background

It's hard to maintain the same information in multiple places and the core team is responsible for policy, while the trainer community and its maintainers are responsible for the IT curriculum. 

There are multiple open issues to this effect on the IT curriculum:
- [definition of official workshops](https://github.com/carpentries/instructor-training/issues/1234)
- [all of the code of conduct related matters](https://github.com/carpentries/instructor-training/projects/3#card-40698780)
- [lots of checkout related issues including conflicting PRs](https://github.com/carpentries/instructor-training/projects/3#card-40699867)

### Pros

- creates a more explicit path for information flow and simplifies maintenance
- ownership comments move content from the experienced community members' memory into explicit locations of the curriculum and handbook, making it easier for new members to contribute to the right place. 
- making it explicit that this is the policy and trainers being transparent about this process might actually streamline the process and reduce the overall load of referencing, eg saying "we're going back to the handbook again" may be less overwhelming than a lot of separate links that trainees think they need to keep every single one of. 

### Cons

- asking other communities to do work that simplifies IT maintenance may be imbalanced
- referring out to other documentation sources is already something that trainees sometimes find overwhelming
- trainers may prefer having the episodes more complete for ease of instruction

## Possible Alternatives

- continue maintaining information in multiple places
- assign an IT maintainer to watch for policy changes (possibly Core team) and open issues PRs

**Comment by karenword** [comment]
Thank you @brownsarahm ! I look forward to the discussion around this. For reference in this discussion, I should note that I have taken some steps in this direction already in ongoing curriculum updates. This includes:

- redirecting to the Workshops and Community pages on Carpentries.org for much of the related content in Carpentries.md (https://github.com/carpentries/instructor-training/pull/1215) -- more could possibly be done here, however. 
- heading the opposite direction to that proposed with the checkout info, but in the same spirit, combining both pages into the episode and deleting the Extras page (still a PR in the sandbox repo https://github.com/data-lessons/instructor-training/pull/43). 

I will also tag in two core team groups whose assistance/support may be needed to address relevant documentation beyond the IT repo, and who may therefore wish to provide feedback during discussion: @carpentries/core-team-workshop-admin @carpentries/core-team-community

**Comment by sheraaronhurt** [comment]
Thanks @karenword I would welcome a discussion to talk about how the WAT can support.
