### ISSUE TITLE
Establish a subcommittee for approved demo lessons

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#83]
## Summary

This proposal is to establish a trainer subcommittee on approved lessons for demos.  This group will work in collaboration with, but separately from other curriculum maintenance to maintain the table of lessons

Initial tasks for this subcommitee will be to:
- Pilot [starting at other points](https://github.com/carpentries/instructor-training/issues/1156)
- document a procedure for adding starting points. 

A member of the leadership panel should lead this, but the additional members should come from outside of the leadership panel. 

## Background

There are a lot of issues around this and the verification of good starting points should probably be a set committee that is not the maintainers.  This would set up in coordination with creating a [checkout policy](https://github.com/carpentries/trainers/issues/84) if that is also approved. 

### Pros

- a separate subcommittee reduces work load
- an explicit policy creates 

### Cons

- too many separate subcommittees could make it hard to coordinate

## Possible Alternatives

- maintainainers hold this power
- leadership keeps this power

**Comment by ha0ye** [comment]
I like not putting the work of identifying demo lessons on maintainers. Especially if there will be a more formalized process for designating episodes as approved demo lessons, that's an additional process that could be handled effectively by a subcommittee focused on that task separately from the work of maintaining lesson content.

**Comment by Denubis** [comment]
I'm willing to run a test of the starting at other points place. I still have my email templates from last time.

**Comment by dvanic** [comment]
> I like not putting the work of identifying demo lessons on maintainers.

I agree with this from the point of view. Maintainers may not be trainers, so may not see the issues/challenges encountered during the demo sessions, and we don't currently have a clean mechanism for providing this sort of feedback.

**Comment by ljvillanueva** [comment]
I'm interested in this idea. I was thinking the other day that I've had issues in the past skipping sections that generate data objects that are required later on. Having intermediary files ready to jump in the middle of a lesson could be a way to tackle both that issue and the demos.

**Comment by brownsarahm** [comment]
> > I like not putting the work of identifying demo lessons on maintainers.
> 
> I agree with this from the point of view. Maintainers may not be trainers, so may not see the issues/challenges encountered during the demo sessions, and we don't currently have a clean mechanism for providing this sort of feedback.

Maintainers of IT currently are all trainers, but still we want more structured space for this process and to distribute the load.

**Comment by karenword** [comment]
I chatted with @ErinBecker about this, and tagging her in for reference. She indicated that the work of identifying and maintaining the core list of usable episodes was something that the Curriculum Team could and probably should be charged with. That would leave the more interesting aspects, e.g. adjusting policy to allow / providing resources to facilitate mid-episode start points for some lessons.

**Comment by brownsarahm** [comment]
That's a more sustainable idea, that the Curriculum team could do this work an ongoing basis.

**Comment by ErinBecker** [comment]
Thanks for tagging me in @karenword. Yes, the Curriculum Team is generally responsible for keeping a birds-eye view of all of the official curricula and are well placed to advise on where appropriate starting points are in a lesson. The only criteria that we have used to date are that trainees can jump into that part of the lesson from a fresh environment (e.g. they don't need to create any intermediate files in advance). If a Trainer subcommittee would like to establish a different or more expansive set of criteria, and let the Curriculum Team know what those curricula are, we (mostly volunteering myself but also possibly @tobyhodges) will be able to keep the list up to date based on those criteria when new official lessons are released.
