### ISSUE TITLE
Create a policy for Checkout process governance

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#84]
## Summary

write a policy that describes how changes to the checkout process occur including what changes can be made by core team, by leadership, and which require a trainer vote. 

An invitation to the trainer community to contribute to this policy should be extended at a trainer meeting. 

## Background

This is a [leadership panel power](https://github.com/carpentries/trainers/blob/main/powers_responsibilities.md) that we should take great care with.  Creating a policy for it that describes how the trainers at large have a say and notification in the process will create more trust. 

### Pros

- greater transparency 

### Cons

- could slow changes or draw contention

## Possible Alternatives

- keep it as a vague power of the leadership panel and use discretion carefully as to how to proceed with changes

**Comment by ACharbonneau** [comment]
WIP

Checkout process: https://carpentries.github.io/instructor-training/checkout/
Likely stakeholder groups: core team, leadership, trainers, maintainers

Key:

- Core pieces of process
   - Modifiers/Scoping
        - Effort: provides effort
-----

- Contributing to materials
   - only specific kinds of contributions but to any repo
   - requires github effort: lesson maintainers
- participate in community
   - in one specific meeting
      - requires interaction effort: trainers
      - requires scheduling effort: core team
- show you can teach
  - From a specific set of lessons/starting points
     - requires interaction effort: trainers
     - requires scheduling effort: core team
- complete within a timeframe
  - 3 months
     - requires tracking effort: core team
- AMY signup
 - N/A
    - requires database effort: core team

-----

Types of possible changes:

- Change Contents of process (drop/add Core pieces of process)
- Change Modifiers/Scoping (Change which repos, and/drop meetings, add/drop lessons)
- Change finer grain requirements (e.g. require that changes be accepted, level of meeting participation, rubric)

**Comment by karenword** [comment]
If the curriculum team takes on primary maintenance of the demo lessons list, this could possibly be combined with #83 .

**Comment by ACharbonneau** [comment]
Should people be able to do their github checkout on in development repos?

**Comment by ACharbonneau** [comment]
Should we send out notifications when the policy changes? 

Do we need a FAQ? 

How do we update the policy page?

Who do you ask these questions?

**Comment by ACharbonneau** [comment]
### Checkout Process Governance

New instructors for the Carpentries are required to complete a checkout process after taking the instructor training course, and prior to becoming fully badged instructors. The current version is available at [checkout process](https://carpentries.github.io/instructor-training/checkout/). 

While the checkout process is written for incoming instructors, there are many other stakeholders in the Carpentries community who are affected by changes to it. This document defines how changes can be made to the checkout process, who should be involved in decisions, and who should be notified when changes occur. In conversation with the Carpentries community, we learned that Trainers want to be kept up to date on changes, and would like to voice their opinions on 'substantial' changes, however they would prefer that 'minor' issues be dealt with by the Trainers Leadership team. The following process tries to take these, and other outcomes from our discussions, into account.

To differentiate 'substantial' from 'minor' changes, we recognize three possible types of change:

1. Change Requirements - add or drop an entire requirement
2. Rescope Requirements - Change which repos, meetings, or lessons are used for checkout
3. Change Participation Requirements - Refine rubric, alter meeting participation expectations, etc

## 1. Change Requirements

If whole requirements for checkout are to be removed, added, or greatly changed, the new proposed checkout process should be written in its entirety and submitted to the Trainer Community as an RFC. The RFC itself should be a PR in the lesson Github to facilitate commenting. The RFC should be advertised in the Trainers Slack channel and the mailing list, and should also be the topic of at least one Trainer meeting during its open comment period. Any feedback should be incorporated either as changes to the proposal or discussed as a comment in the PR conversation to recognize that the feedback was considered and why it was not incorporated.

Once the RFC is ready, it should have a final approval by the Trainers Leadership before merge. Once merged, the updates should be updated in any other documentation as appropriate (FAQs, handbook, etc), and an announcement should be made to the entire Carpentries community noting the change. The announcement should be done at least in Slack, the mailing list, and the next Trainer meeting.

## 2. Rescope Requirements

Rescoping changes should use the existing Trainers Leadership mechanism to propose and adopt changes, however the Trainers Leadership should explicitly discuss whether the proposed change is large or disruptive enough to warrant community input. If Leadership feels that the change will be large or decisive, it should be treated using the Change Requirements process. If the changes are minor, they should be dealt with using the Change Participation Requirements.

## 3. Change Participation Requirements

For these minor changes, proposals should use the existing Trainers Leadership mechanism to propose and adopt changes. When changes are finalized, updates should be updated in any other documentation as appropriate (FAQs, handbook, etc), and an announcement should be made to the entire Carpentries community noting the change. The announcement should be done at least in Slack, the mailing list, and the next Trainer meeting.

**Comment by arinbasu** [comment]
Nothing to add
