### ISSUE TITLE
Trainer Leadership Minutes Procedure

### ISSUE THREAD

**Issue by ACharbonneau** [carpentries/trainers#88]
## Title 

Defining what information will be kept private to the Trainers Leadership, and what will be shared with the Trainers community. 

## Summary

This proposal is that the default for Trainer Leadership outputs will be 'open': Only meeting minutes will be subject to redaction, and redactions to the minutes will only be done for special cases such as Trainers Application decisions.

## Specific Minutes Sharing Procedure

- Proposals for upcoming meetings will be submitted as issues in the public trainers repository, and are always viewable by everyone
- Meeting minutes will be taken in a private space that is limited to Trainer Leadership
- During each meeting, as topics are discussed the group will decide if the upcoming topic should be redacted. If so, notes will not be recorded. Meeting minutes will be briefly discussed at the end of each meeting to determine if further redactions are needed
- the Secretary will make a Pull request to the public trainers repository with the public meeting notes
- Approval/edits of the minutes by Trainers Leadership will proceed from there 

Important notes:
- Unredacted minutes will never be posted to GitHub
- Names of Trainer Leadership (who said what) will not be redacted
- Names and identifying details of non-Leadership persons under discussion will sometimes be redacted. 
- Content associated with names and identifying details of non-Leadership persons under discussion will sometimes be redacted.
   - Redactions will only be made for identifying information that may adversely affect the person under discussion. This includes but is not necessarily limited to: Trainers Application decisions and recruitment decisions. Conversations that feature a great deal of identifying information may be redacted in full as in `<trainer applications were discussed>`
- Trainer Leadership is not *required* to redact identifying information in cases where the benefit to disclosing that information to the Trainer Community would outweigh any negatives, such as offering congratulations. 
- This procedure is subject to any applicable Carpentries privacy policies, and in cases where they conflict the Carpentries Privacy Polices always take precedence.

## Background

The Trainers Leadership expects that most of the topics of our meetings will be of potential interest to the Trainers community and should be shared broadly. However, we recognize that there will occasionally be meetings that will contain sensitive information that should not be made public. In these cases, the Trainers Leadership needs a procedure for deciding what topics that are subject to redactions.

### Pros

- Having a clear procedure allows for better transparency of how Trainers Leadership works
- Having a procedure allows the Trainers Leadership to protect the identities of people who might be under discussion
- Redacting the names of individuals from discussions about application decisions and similar protects those individuals from potential future bias should they apply again

### Cons

- Redacted information will not be available to the Trainer Community
- A too little sharing could disallow the Trainers Leadership from issuing congratulations or similar to individuals
- A too little sharing would reduce the transparency of decisions made by Trainers Leadership 
- Too much sharing could create bias in future decisions 
 
## Possible Alternatives

- All meeting minutes could always be open to all trainers
- All meeting minutes could default to closed to all trainers

**Comment by ACharbonneau** [comment]
Email comment from Mark that I didn't incorporate, because I'm not sure how. Should discuss in meeting:

>The other thing was around publishing items to trainers but not more broadly. I was thinking it could be worded along the lines of “minutes will be restricted to the trainer community if publishing them more broadly may affect the integrity of the trainer and instructor training and selection programs”. This would cover issues like the trainer selection process, instructor checkout evaluation, and the like that we were discussing earlier.

**Comment by ACharbonneau** [comment]
I've updated to include larger redactions of sections, and will continue updating based on new comments

**Comment by marklcrowe** [comment]
Hi Amanda, I've just made a minor edit because it occurred to me that there may occasionally be confidential information discussed by the leadership group that we should not make generally available that is not related to personal identification. Could be something as innocuous as "we've got a grant from funding organisation X, but we're not allowed to tell anyone until the official press release". I think we need to recognise that as a possibility and allow for it within our policy.

**Comment by marklcrowe** [comment]
With regards to attribution of comments to leadership group members, I think Jeff had a good way of addressing it in the chat - something like "Names of Trainer Leadership will not be redacted unless it's likely to be detrimental to the individual or others, or compromise confidential information". Although I think he phrased it better than that :-) I would prefer a specific reason like this rather than a more general "Names will generally not be redacted". Related to this, should a member of the leadership group be able to request an 'off the record' discussion? In principle I'm not a great fan of that idea, but there's always the possibility of something coming in front of the group which makes it necessary, and we should perhaps prepare for that situation.

**Comment by brownsarahm** [comment]
Re: "off the record" I similarly am not a big fan, but have felt that maybe we need the option. The only topic I've been able to come up with is if we were discussing interpersonal matters about one another. If it went to a vote for removal, that should be recorded with a consensus for cause, but maybe not in great detail, and other conversations may not be fruitful to record at all.

**Comment by ACharbonneau** [comment]
Thanks! I'm delighted to have people edit it directly. The funding example is really helpful. One of the things I'm finding difficult about finding the right language is that it's based on my conjecture of what things we will talk about, but I don't really know what sorts of things we'll actually talk about :)

I feel the same way about the off the record idea. I haven't been able to come up with a scenario where it would make sense, so I'm not sure whether I'm just not imaginative enough and we should have it just in case, or whether it makes too much potential secrecy where it isn't needed.

**Comment by jcoliver** [comment]
In prior versions, we had the following statement in the Important Notes section: 

> Redactions will only be made for identifying information that may adversely affect the person under discussion.

I like this broad language. It provides a fair amount of flexibility, acknowledging the subjectivity of deciding what is "adverse". This could include comments made by Trainers Leadership that could have an adverse effect on that member of the Trainers Leadership committee. I think it provides the _only_ reason (albeit a vague reason) for redactions.

**Comment by maneesha** [comment]
Thanks all for starting this conversation! Within The Carpentries Core Team, we are in the process developing organization wide privacy policies.  We also recognize that in any workflows, there will be things that are driven by _policy_ and things that are driven by _guidelines_ or _recommendations_.

We would like to be sure that any sub-group's workflows and communication norms fit what The Carpentries is doing as a whole.  I really appreciate that the Trainers Leadership is thinking about this and you are welcome to continue brainstorming! I would ask that we not release anything (whether in the form of policy or guidelines) until Carpentries-wide policies are in place.

Questions about this can be directed to me or @fmichonneau

**Comment by brownsarahm** [comment]
I think that the most appropriate thing for us to do is to rename this.  This shouldn't be in conflict with the carpentries policy and we will follow carpentries policies as appropriate.  This is really something much, much, more specific, it's just our promise to the trainers community about what our minutes will contain.  

Can we rename this and add that it is subject to carpentries policies and then proceed?

**Comment by ACharbonneau** [comment]
Hey @karenword did you have a verdict on how much I need to change this?

**Comment by karenword** [comment]
I think it should be fine to reframe this as a procedural statement describing how notes will generally be handled during and after Leadership meetings rather than documentation of policy or guidelines. @maneesha, please chime in if I am overlooking anything.

**Comment by karenword** [comment]
To be more specific, I think the re-titling is good, and maybe replacing "procedures" where "policy" is used in the text would make it more clear.

**Comment by ACharbonneau** [comment]
I've changed at lot of words. I think it's good to be on our next agenda
